import {APP_VERSION,appConfig} from './config.js';import {Auth} from './auth.js';import {toast} from './ui.js';import * as QR from './qr.js';import * as Abs from './baovang.js';import * as Score from './chamdiem.js';import * as Stats from './thongke.js';import * as Rank from './xeploai.js';import * as Admin from './admin.js';
const pages=['qr','baovang','chamdiem','thongke','xeploai','quantri'];let active='';
const $=id=>document.getElementById(id);
function renderUser(){const u=Auth.currentUser;$('userBox').innerHTML=u?`<div><strong>${u.ho_ten}</strong><small>${u.ma_cb} · ${u.vai_tro}</small></div>`:''}
function allowed(k){return Auth.hasTab(k)}
async function open(k){if(!allowed(k))return toast('Tài khoản chưa được cấp quyền chức năng này.','err');active=k;document.querySelectorAll('.main-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===k));pages.forEach(x=>$(`page-${x}`).classList.add('hidden'));$(`page-${k}`).classList.remove('hidden');if(k==='qr')await QR.init($('page-qr'));if(k==='baovang')await Abs.init($('page-baovang'));if(k==='chamdiem')await Score.init($('page-chamdiem'));if(k==='thongke')await Stats.init($('page-thongke'));if(k==='xeploai')await Rank.init($('page-xeploai'));if(k==='quantri')await Admin.init($('page-quantri').querySelector('#adminContent'))}
function session(){ $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');renderUser();document.querySelectorAll('.main-tab').forEach(b=>b.classList.toggle('hidden',!allowed(b.dataset.tab)));const first=pages.find(allowed);if(first)open(first);else toast('Tài khoản chưa được cấp quyền nào.','err')}
function bind(){ $('loginForm').onsubmit=async e=>{e.preventDefault();const er=$('loginError');er.textContent='';const r=await Auth.login($('username').value,$('password').value,false);if(!r.ok)return er.textContent=r.message;session()};$('logoutBtn').onclick=()=>{Auth.logout();location.reload()};document.querySelectorAll('.main-tab').forEach(b=>b.onclick=()=>open(b.dataset.tab))}
window.App={Auth,toast,open};$('username').value=Auth.remembered();bind();if(Auth.restore())session();console.info(`QLNN ${APP_VERSION}`,appConfig);
