import {supabase,appConfig,managedClasses,canManageAbsence,canMonitorAbsence} from './config.js?v=3.0.5.25.33';
import {esc,toast} from './ui.js?v=3.0.5.25.33';

let root,grades=[],classes=[],students=[],roster=[];
let selectedGrade='',selectedClass='',date='',buoi='Sáng',autoBuoi='Sáng',manualBuoi=false;

function normText(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function gradeKey(v){const m=String(v==null?'':v).match(/(?:khoi|khối)?\s*(10|11|12)/i);return m?m[1]:normText(v).replace(/[^0-9]/g,'')}
function gradeLabel(v){const k=gradeKey(v);return k?'Khối '+k:String(v==null?'':v).trim()}
function sameGrade(a,b){const x=gradeKey(a),y=gradeKey(b);return x!==''&&x===y}
function activeStudent(r){const s=normText(r&&r.trang_thai);return !s||['active','dang hoc','đang học','hoc','học','true','1'].includes(s)}
function naturalSort(a,b){return String(a).localeCompare(String(b),'vi',{numeric:true,sensitivity:'base'})}
function localDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day}
function formatDate(v){if(!v)return '';const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?m[3]+'/'+m[2]+'/'+m[1]:String(v)}
function showError(message){if(root&&root.querySelector('#absRows'))root.querySelector('#absRows').innerHTML='<div class="danger-box">'+esc(message)+'</div>'}
function rejectWrite(title,message){toast(title+': '+message,'err')}
function classRoster(){const map=new Map();for(const r of roster){if(!activeStudent(r)||!r.lop)continue;const lop=String(r.lop).trim();if(!map.has(lop))map.set(lop,{lop:lop,khoi:gradeLabel(r.khoi||r.lop)});}return Array.from(map.values())}

async function fetchAll(factory,chunk){const size=chunk||1000,all=[];let from=0;while(true){const q=await factory().range(from,from+size-1);if(q.error)throw q.error;const rows=q.data||[];all.push(...rows);if(rows.length<size)break;from+=size;}return all}

export async function init(r){
 root=r;const now=new Date();date=localDate(now);autoBuoi=await detectCurrentSession(now);buoi=autoBuoi;
 selectedGrade='';selectedClass='';students=[];roster=[];manualBuoi=false;
 await renderShell();await loadGrades();if(canMonitorAbsence(window.App&&window.App.Auth?window.App.Auth.currentUser:null))await loadMonitor();
}

async function renderShell(){
 const user=window.App&&window.App.Auth?window.App.Auth.currentUser:null;const monitor=canMonitorAbsence(user);
 root.innerHTML='<div class="page-head"><div><h2>Báo Vắng Học Sinh</h2><p>Chọn khối → lớp → số học sinh vắng. Lớp vẫn phải báo kể cả khi không có học sinh vắng.</p></div><span class="badge ok">Năm học '+esc(appConfig.namHoc)+'</span></div>'+
 '<div class="absence-top-grid">'+
 '<div class="absence-box"><div class="selector-title">📅 Thời gian báo vắng</div><div class="absence-inline"><label>Ngày<input id="absDate" type="date" value="'+date+'"></label></div><div class="auto-session-line"><b>Buổi hệ thống:</b> <span id="autoBuoiLabel">'+esc(autoBuoi)+'</span> <span class="badge">Tự động</span></div><div class="selector-hint">Mặc định: buổi chiều bắt đầu <b>14:00, từ tiết 2</b>. Có thể chọn “Báo bổ sung” nếu cần báo lại.</div><label class="manual-session-toggle"><input id="absManualBuoi" type="checkbox"> Báo bổ sung / chọn lại buổi</label><select id="absBuoi" disabled aria-label="Buổi bổ sung"><option value="Sáng" '+(buoi==='Sáng'?'selected':'')+'>Sáng</option><option value="Chiều" '+(buoi==='Chiều'?'selected':'')+'>Chiều</option></select></div>'+
 '<div class="absence-box"><div class="selector-title">👥 Chọn khối</div><div id="absGradeRadios" class="absence-grade-grid"><span class="class-empty">Đang tải...</span></div></div>'+
 '<div class="absence-box"><div class="selector-title">🏫 Chọn lớp</div><div id="absClassRadios" class="absence-class-grid"><span class="class-empty">Hãy chọn khối trước.</span></div></div>'+
 '<div class="absence-box"><div class="selector-title">👤 Số vắng</div><select id="absCount" disabled><option value="">-- Chọn lớp trước --</option></select><div id="absClassInfo" class="selector-hint">Chưa chọn lớp.</div></div></div>'+
 '<div id="absRows"><div class="empty">Hãy chọn khối, lớp và số học sinh vắng.</div></div>'+(monitor?'<div id="absenceMonitor" class="absence-monitor-wrap"></div>':'');
 root.querySelector('#absDate').onchange=function(e){date=e.target.value;if(monitor)loadMonitor()};
 root.querySelector('#absManualBuoi').onchange=function(e){manualBuoi=e.target.checked;const sel=root.querySelector('#absBuoi');sel.disabled=!manualBuoi;if(manualBuoi)sel.value=buoi;else{buoi=autoBuoi;sel.value=autoBuoi}if(monitor)loadMonitor()};
 root.querySelector('#absBuoi').onchange=function(e){buoi=e.target.value;if(monitor)loadMonitor()};
 root.querySelector('#absCount').onchange=renderRows;
}

async function loadGrades(){try{roster=await fetchAll(function(){return supabase.from('danh_sach').select('ma_hs,ho_ten,khoi,lop,ngay_sinh,trang_thai').not('lop','is',null).order('lop')});roster=roster.filter(activeStudent);const keys=Array.from(new Set(roster.map(function(x){return gradeKey(x.khoi||x.lop)}).filter(Boolean))).sort(function(a,b){return Number(a)-Number(b)});grades=keys.map(function(k){return 'Khối '+k});root.querySelector('#absGradeRadios').innerHTML=grades.map(function(g){return '<label class="absence-grade"><input type="radio" name="absGrade" value="'+esc(g)+'"><span>'+esc(g)+'</span></label>'}).join('')||'<span class="class-empty">Không tìm thấy học sinh đang học.</span>';root.querySelectorAll('input[name="absGrade"]').forEach(function(r){r.onchange=function(){onGradeChange(r.value)}})}catch(e){showError(e.message)}}

async function onGradeChange(grade){
 selectedGrade=gradeLabel(grade);selectedClass='';students=[];const classBox=root.querySelector('#absClassRadios'),count=root.querySelector('#absCount');count.disabled=true;count.innerHTML='<option value="">-- Chọn lớp trước --</option>';root.querySelector('#absRows').innerHTML='<div class="empty">Hãy chọn lớp và số học sinh vắng.</div>';
 const all=classRoster().filter(function(x){return sameGrade(x.khoi,selectedGrade)});classes=Array.from(new Set(all.map(function(x){return x.lop}))).sort(naturalSort);const scope=managedClasses(window.App&&window.App.Auth?window.App.Auth.currentUser:null);if(scope!==null)classes=classes.filter(function(c){return scope.includes(c)});
 classBox.innerHTML=classes.map(function(c){return '<label class="absence-class"><input type="radio" name="absClass" value="'+esc(c)+'"><span>'+esc(c)+'</span></label>'}).join('')||'<span class="class-empty">Không có lớp trong phạm vi tài khoản.</span>';
 root.querySelectorAll('input[name="absClass"]').forEach(function(r){r.onchange=function(){onClassChange(r.value)}});
}

async function onClassChange(cls){selectedClass=cls;try{students=roster.filter(activeStudent).filter(function(s){return String(s.lop||'').trim()===String(cls).trim()&&sameGrade(s.khoi||s.lop,selectedGrade)});students.sort(function(a,b){return String(a.ho_ten||'').localeCompare(String(b.ho_ten||''),'vi',{sensitivity:'base'})});const count=root.querySelector('#absCount');count.disabled=false;count.innerHTML='<option value="">-- Chọn số học sinh vắng --</option>'+Array.from({length:students.length+1},function(_,i){return '<option value="'+i+'">'+i+'</option>'}).join('');root.querySelector('#absClassInfo').innerHTML='<b>'+esc(cls)+'</b> · '+students.length+' học sinh · <b>0</b> cũng phải được ghi nhận.';root.querySelector('#absRows').innerHTML='<div class="empty">Chọn số vắng. Nếu không có học sinh vắng, chọn <b>0</b> để xác nhận lớp đã báo.</div>'}catch(e){showError(e.message)}}

function absenceRow(index){let opts='<option value="">-- Chọn học sinh --</option>';students.forEach(function(s,i){opts+='<option value="'+i+'">'+esc(s.ho_ten)+' — '+formatDate(s.ngay_sinh)+'</option>'});return '<div class="absence-row" data-row="'+index+'"><div class="absence-index">'+(index+1)+'</div><div class="absence-student-wrap"><label>Học sinh<select class="absence-student">'+opts+'</select></label></div><div class="absence-status"><span class="status-label">Trạng thái</span><label class="absence-status-radio allowed"><input type="radio" name="absStatus_'+index+'" value="Vắng có phép"><span>✓ Có phép</span></label><label class="absence-status-radio notallowed"><input type="radio" name="absStatus_'+index+'" value="Vắng không phép"><span>✕ Không phép</span></label></div></div>'}
function renderRows(){const sel=root.querySelector('#absCount'),body=root.querySelector('#absRows');if(sel.value===''){body.innerHTML='<div class="empty">Hãy chọn số học sinh vắng.</div>';return}const count=Number(sel.value||0);if(count===0){body.innerHTML='<div class="absence-panel zero-report"><div class="zero-icon">✓</div><div><h3>Không có học sinh vắng</h3><p>Lớp <b>'+esc(selectedClass)+'</b> sẽ được ghi nhận là <b>vắng 0</b> cho '+esc(buoi)+' ngày '+formatDate(date)+'.</p></div><button id="absSaveZero" class="btn primary">💾 Xác nhận lớp không có học sinh vắng</button></div>';root.querySelector('#absSaveZero').onclick=saveZero;return}body.innerHTML='<div class="absence-panel"><div class="page-head"><div><h3 style="margin:0">Danh sách học sinh vắng — '+esc(selectedClass)+'</h3><p>'+count+' học sinh cần xác nhận trạng thái.</p></div><span class="badge">'+count+' dòng</span></div><div class="absence-list">'+Array.from({length:count},function(_,i){return absenceRow(i)}).join('')+'</div><div class="action-row"><button id="absSave" class="btn primary">💾 Ghi nhận '+count+' học sinh vắng</button></div></div>';root.querySelectorAll('.absence-student').forEach(function(s){s.onchange=updateStudentOptions});root.querySelectorAll('input[name^="absStatus_"]').forEach(function(r){r.onchange=updateStatusVisual});root.querySelector('#absSave').onclick=save}
function updateStudentOptions(){const selects=Array.from(root.querySelectorAll('.absence-student')),selected=new Set(selects.map(function(s){return s.value}).filter(Boolean));selects.forEach(function(sel){Array.from(sel.options).forEach(function(opt){if(opt.value)opt.disabled=selected.has(opt.value)&&opt.value!==sel.value})})}
function updateStatusVisual(){root.querySelectorAll('.absence-row').forEach(function(row){const chosen=row.querySelector('input[type="radio"]:checked')?.value||'';row.classList.toggle('has-permission',chosen==='Vắng có phép');row.classList.toggle('has-no-permission',chosen==='Vắng không phép')})}

async function save(){const u=window.App&&window.App.Auth?window.App.Auth.currentUser:null;if(!canManageAbsence(u,selectedClass)){rejectWrite('Không được phép báo vắng','Tài khoản hiện tại không có quyền báo vắng cho lớp '+selectedClass+'. Hệ thống không ghi dữ liệu vào CSDL.');return}if(!(await classHasSchedule(selectedClass,date,buoi))){rejectWrite('Không ghi báo vắng','Lớp '+selectedClass+' chưa có lịch học '+buoi+' ngày '+formatDate(date)+' trong TKB. Hệ thống không ghi dữ liệu vào CSDL.');return}const rows=Array.from(root.querySelectorAll('.absence-row')),payload=[];for(const row of rows){const idx=row.querySelector('.absence-student').value,status=row.querySelector('input[type="radio"]:checked')?.value||'';if(idx===''){toast('Dòng '+(Number(row.dataset.row)+1)+': chưa chọn học sinh.','err');return}if(!status){toast('Dòng '+(Number(row.dataset.row)+1)+': chưa chọn Có phép/Không phép.','err');return}const s=students[Number(idx)];payload.push({ma_hs:s.ma_hs,ho_ten:s.ho_ten,khoi:s.khoi,lop:s.lop,ngay_diem_danh:date,buoi:buoi,trang_thai:status,chi_tiet:null,diem:0,ma_nguoi_cap_nhat:u&&u.ma_cb?u.ma_cb:null,ten_nguoi_cap_nhat:u&&u.ho_ten?u.ho_ten:null})}const q=await supabase.from('diem_danh_master').insert(payload);if(q.error){toast('Không ghi được dữ liệu: '+q.error.message,'err');return}const er=await saveClassReport(payload.length);if(er){toast('Đã ghi học sinh nhưng chưa cập nhật trạng thái lớp: '+er,'err');return}toast('Đã ghi nhận '+payload.length+' học sinh vắng.','ok');resetAfterSave()}
async function saveZero(){const u=window.App&&window.App.Auth?window.App.Auth.currentUser:null;if(!canManageAbsence(u,selectedClass)){rejectWrite('Không được phép báo vắng','Tài khoản hiện tại không có quyền báo vắng cho lớp '+selectedClass+'. Hệ thống không ghi dữ liệu vào CSDL.');return}if(!(await classHasSchedule(selectedClass,date,buoi))){rejectWrite('Không ghi báo vắng','Lớp '+selectedClass+' chưa có lịch học '+buoi+' ngày '+formatDate(date)+' trong TKB. Hệ thống không ghi dữ liệu vào CSDL.');return}const er=await saveClassReport(0);if(er){toast(er,'err');return}toast('Đã xác nhận '+selectedClass+': vắng 0.','ok');resetAfterSave()}

async function saveClassReport(count){const base={nam_hoc:appConfig.namHoc,ngay_bao:date,buoi:buoi,khoi:selectedGrade,lop:selectedClass,so_vang:count};const q=await supabase.from('bao_vang_lop').select('nam_hoc,ngay_bao,buoi,khoi,lop,so_vang').eq('nam_hoc',appConfig.namHoc).eq('ngay_bao',date).eq('buoi',buoi).eq('lop',selectedClass).limit(1);if(q.error)return 'Không đọc được trạng thái báo vắng của lớp: '+q.error.message;if(q.data&&q.data.length){const u=await supabase.from('bao_vang_lop').update(base).eq('nam_hoc',appConfig.namHoc).eq('ngay_bao',date).eq('buoi',buoi).eq('lop',selectedClass);return u.error?u.error.message:null}const i=await supabase.from('bao_vang_lop').insert(base);return i.error?i.error.message:null}
function resetAfterSave(){const c=root.querySelector('#absCount');if(c)c.value='';const b=root.querySelector('#absRows');if(b)b.innerHTML='<div class="empty">Đã ghi nhận. Có thể chọn số vắng cho lượt tiếp theo.</div>';if(canMonitorAbsence(window.App&&window.App.Auth?window.App.Auth.currentUser:null))loadMonitor()}

async function loadMonitor(){const box=root.querySelector('#absenceMonitor');if(!box)return;box.innerHTML='<div class="panel"><div class="empty">Đang tải theo dõi báo vắng...</div></div>';try{const scheduled=await scheduledClasses(date,buoi);const q=await fetchAll(function(){return supabase.from('bao_vang_lop').select('lop,so_vang').eq('nam_hoc',appConfig.namHoc).eq('ngay_bao',date).eq('buoi',buoi)});const reportMap=new Map(q.map(function(x){return [String(x.lop),x]}));const done=scheduled.filter(function(x){return reportMap.has(x.lop)}),pending=scheduled.filter(function(x){return !reportMap.has(x.lop)});let html='<div class="panel absence-monitor"><div class="page-head"><div><h3 style="margin:0">📋 Theo dõi báo vắng — '+esc(date)+' · '+esc(buoi)+'</h3><p>Dựa trên các lớp có lịch học; lớp không có học sinh vắng vẫn phải có bản ghi “vắng 0”.</p></div><button id="monitorRefresh" class="btn light">↻ Cập nhật</button></div>';if(!scheduled.length)html+='<div class="notice warn"><b>Chưa có dữ liệu lớp có lịch.</b> Hãy khai báo TKB cho đúng ngày và buổi.</div>';html+='<div class="monitor-cards"><button class="monitor-card total"><b>'+scheduled.length+'</b><span>Số lớp có lịch</span></button><button class="monitor-card done"><b>'+done.length+'</b><span>Đã báo</span></button><button id="pendingBtn" class="monitor-card pending"><b>'+pending.length+'</b><span>Chưa báo</span></button></div><div id="pendingList" class="pending-list '+(pending.length?'hidden':'')+'">'+(pending.length?pending.map(function(x){return '<button class="pending-class">'+esc(x.lop)+'</button>'}).join(''):'<span class="empty">'+(scheduled.length?'Tất cả lớp đã báo.':'Chưa xác định được lớp có lịch.')+'</span>')+'</div><div class="table-wrap"><table class="table"><thead><tr><th>Lớp</th><th>Trạng thái</th><th>Số vắng</th></tr></thead><tbody>'+scheduled.map(function(x){const r=reportMap.get(x.lop);return '<tr><td><b>'+esc(x.lop)+'</b></td><td>'+(r?'<span class="badge ok">Đã báo</span>':'<span class="badge warn">Chưa báo</span>')+'</td><td>'+(r?esc(r.so_vang):'—')+'</td></tr>'}).join('')+'</tbody></table></div></div>';box.innerHTML=html;box.querySelector('#monitorRefresh').onclick=loadMonitor;box.querySelector('#pendingBtn').onclick=function(){box.querySelector('#pendingList').classList.toggle('hidden')}}catch(e){box.innerHTML='<div class="danger-box">Không tải được theo dõi báo vắng: '+esc(e.message)+'</div>'}}

async function scheduledClasses(day,session){const d=new Date(day+'T12:00:00');const dow=d.getDay(),thu=dow===0?8:dow+1;const q=await supabase.from('thoi_khoa_bieu').select('lop,khoi,thu,buoi,trang_thai').eq('nam_hoc',appConfig.namHoc).eq('thu',thu).eq('buoi',session);if(q.error)throw q.error;const rows=(q.data||[]).filter(function(r){const st=normText(r.trang_thai);return !st||st==='hoat dong'||st==='active'||st==='true'||st==='1'}),out=new Map(),all=classRoster();for(const r of rows){const khoi=String(r.khoi||'').trim(),lop=String(r.lop||'').trim();if(lop){out.set(lop,{lop:lop,source:'Lớp '+lop});continue}if(khoi){for(const c of all){if(sameGrade(c.khoi,khoi))out.set(c.lop,{lop:c.lop,source:gradeLabel(khoi)+' — áp dụng toàn khối'})}}else{for(const c of all)out.set(c.lop,{lop:c.lop,source:'Toàn trường'})}}const scope=managedClasses(window.App&&window.App.Auth?window.App.Auth.currentUser:null);let a=Array.from(out.values());if(scope!==null)a=a.filter(function(x){return scope.includes(x.lop)});return a.sort(function(a,b){return naturalSort(a.lop,b.lop)})}
async function classHasSchedule(cls,day,session){if(!cls||!session)return false;const list=await scheduledClasses(day,session);return list.some(function(x){return x.lop===String(cls).trim()})}
async function detectCurrentSession(now){const t=now.toTimeString().slice(0,8);try{const q=await supabase.from('cai_dat_thoi_gian').select('buoi,gio_bat_dau_diem_danh,gio_ket_thuc_diem_danh').eq('nam_hoc',appConfig.namHoc).eq('trang_thai','Học');if(!q.error){const hit=(q.data||[]).find(function(x){const a=String(x.gio_bat_dau_diem_danh||'').slice(0,8),b=String(x.gio_ket_thuc_diem_danh||'').slice(0,8);return a&&b&&a<=t&&t<=b});if(hit&&hit.buoi)return hit.buoi}}catch(e){}const hm=now.getHours()*60+now.getMinutes();if(hm>=840&&hm<=1110)return 'Chiều';if(hm>=360&&hm<780)return 'Sáng';return hm<840?'Sáng':'Chiều'}
