import {supabase,appConfig} from './config.js?v=3.0.5.25.36';
import {esc,toast,formatDateVN,compareVietnameseFullName} from './ui.js?v=3.0.5.25.36';
const subjects=['Toán','Văn','Tiếng Anh','Vật lý','Hoá học','Sinh học','Lịch Sử','Địa lý','GD KTPL','Tin học'];
export async function init(root,user,logout){
 const isStudent=user.portalRole==='student';
 root.innerHTML=`<header class="portal-top"><div><div class="portal-eyebrow">THPT Lê Hồng Phong · ${esc(appConfig.namHoc)}</div><h1>${isStudent?'Cổng thông tin học sinh':'Cổng thông tin phụ huynh'}</h1><p>Theo dõi kết quả học tập, kiểm tra và nề nếp</p></div><button id="portalLogout" class="btn light">Đăng xuất</button></header><div class="portal-content"><section class="portal-profile" id="portalProfile">Đang tải thông tin học sinh...</section><div class="portal-tabs"><button class="active" data-tab="results">📘 Kết quả kiểm tra</button><button data-tab="discipline">📋 Nề nếp & thi đua</button></div><section id="portal-results" class="portal-panel"></section><section id="portal-discipline" class="portal-panel hidden"></section></div>`;
 root.querySelector('#portalLogout').onclick=logout;
 root.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));root.querySelectorAll('.portal-panel').forEach(x=>x.classList.add('hidden'));root.querySelector('#portal-'+btn.dataset.tab).classList.remove('hidden');});
 const {data,error}=await supabase.rpc('portal_lay_du_lieu_v3',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||'',p_doi_tuong:isStudent?'Học sinh':'Phụ huynh'});
 if(error||!data){root.querySelector('#portalProfile').innerHTML=`<div class="danger-box">Không tải được dữ liệu: ${esc(error?.message||'Không tìm thấy tài khoản')}. Hãy chạy SQL migration 021.</div>`;return;}
 const student=data.hoc_sinh||{};const results=data.ket_qua||[];const attendance=data.ne_nep||[];const appeals=data.phuc_khao||[];const notices=data.thong_bao||[];
 renderNotifications(root,notices,user);
 root.querySelector('#portalProfile').innerHTML=`<div class="portal-avatar">🎓</div><div class="portal-student-meta"><h2>${esc(student.ho_ten||user.ho_ten)}</h2><p>Mã học sinh: <b>${esc(student.ma_hs||user.ma_hs)}</b> · Lớp <b>${esc(student.lop||'')}</b> · Khối ${esc(student.khoi||'')}</p></div><div class="portal-summary"><div><small>Thông báo chưa đọc</small><b>${notices.filter(n=>!n.da_doc_at).length}</b></div><div><small>Bài kiểm tra có điểm</small><b>${results.length}</b></div><div><small>Lượt nề nếp</small><b>${attendance.length}</b></div></div>`;
 renderResults(root.querySelector('#portal-results'),results,isStudent,appeals,user);
 renderDiscipline(root.querySelector('#portal-discipline'),attendance);

}
function renderNotifications(root,rows,user){
 const ordered=[...rows].sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));const unread=ordered.filter(x=>!x.da_doc_at);const ticker=(unread.length?unread:ordered.filter(x=>x.hien_chay_ngang!==false).slice(0,1));
 const old=root.querySelector('.portal-notice-area');old?.remove();
 const area=document.createElement('section');area.className='portal-notice-area';
 area.innerHTML=`${ticker.length?`<div class="portal-ticker"><b>📢 Thông báo</b><div class="portal-ticker-track"><span>${[...ticker,...ticker].map(x=>esc(x.tieu_de+' — '+x.noi_dung)).join('　　◆　　')}</span></div></div>`:''}<div class="portal-notice-head"><h2>🔔 Thông báo <span class="badge ${unread.length?'warn':'ok'}">${unread.length} chưa đọc</span></h2><button class="btn light" id="noticeToggle">${rows.length?'Xem danh sách':'Chưa có thông báo'}</button></div><div class="portal-notice-list hidden" id="portalNoticeList">${rows.length?rows.map(n=>`<article class="portal-notice-item ${n.da_doc_at?'read':'unread'}"><div class="notice-item-title">${esc(n.tieu_de)} <small>${esc(formatDateVN(n.created_at,true))}</small></div><p>${esc(n.noi_dung)}</p><div class="notice-item-foot">${esc(n.loai||'Thông báo')} · ${esc(n.nguoi_gui||'Nhà trường')}${!n.da_doc_at?` <button class="btn light notice-read" data-id="${n.id}">Đánh dấu đã đọc</button>`:''}</div></article>`).join(''):'<div class="empty">Chưa có thông báo.</div>'}</div>`;
 const content=root.querySelector('.portal-content');content?.prepend(area);
 area.querySelector('#noticeToggle').onclick=()=>area.querySelector('#portalNoticeList').classList.toggle('hidden');
 area.querySelectorAll('.notice-read').forEach(btn=>btn.onclick=async()=>{const {data,error}=await supabase.rpc('portal_danh_dau_da_doc_v2',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||'',p_ids:[Number(btn.dataset.id)],p_doi_tuong:user.portalRole==='student'?'Học sinh':'Phụ huynh'});if(error||!data?.ok)return toast(error?.message||data?.message||'Không cập nhật được trạng thái đọc.','err');const row=rows.find(x=>String(x.id)===btn.dataset.id);if(row)row.da_doc_at=new Date().toISOString();renderNotifications(root,rows,user);});
 if(unread.some(n=>n.hien_popup)){const n=unread.find(x=>x.hien_popup);const overlay=document.createElement('div');overlay.className='portal-notice-overlay';overlay.innerHTML=`<div class="portal-notice-modal"><div class="portal-notice-modal-icon">📣</div><h2>${esc(n.tieu_de)}</h2><p>${esc(n.noi_dung)}</p><small>${esc(formatDateVN(n.created_at,true))}</small><div class="action-row"><button class="btn light" id="noticeLater">Để sau</button><button class="btn primary" id="noticeAck">Đã nắm thông tin</button></div></div>`;root.appendChild(overlay);const mark=async()=>{const {data,error}=await supabase.rpc('portal_danh_dau_da_doc_v2',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||'',p_ids:[Number(n.id)],p_doi_tuong:user.portalRole==='student'?'Học sinh':'Phụ huynh'});if(!error&&data?.ok)n.da_doc_at=new Date().toISOString();overlay.remove();renderNotifications(root,rows,user);};overlay.querySelector('#noticeLater').onclick=()=>overlay.remove();overlay.querySelector('#noticeAck').onclick=mark;}
}
function renderResults(el,rows,isStudent,appeals,user){
 const rounds=[...new Set(rows.map(r=>r.dot_kiem_tra).filter(Boolean))];
 el.innerHTML=`<div class="portal-section-head"><div><h2>Kết quả kiểm tra, khảo sát</h2><p>Điểm trắc nghiệm, tự luận và điểm toàn bài. Trong thời hạn quy định, học sinh tích chọn đúng phần muốn phúc khảo.</p></div><select id="resultRound"><option value="">Tất cả các đợt</option>${rounds.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="resultTable"></div><div id="appealInlineMessage" role="status" class="appeal-inline-message"></div>`;
 const draw=()=>{const round=el.querySelector('#resultRound').value;const list=rows.filter(x=>!round||x.dot_kiem_tra===round);if(!list.length){el.querySelector('#resultTable').innerHTML='<div class="empty">Chưa có kết quả kiểm tra được đăng tải.</div>';return;}const groups={};list.forEach(r=>(groups[r.dot_kiem_tra]??=[]).push(r));el.querySelector('#resultTable').innerHTML=Object.entries(groups).map(([name,rs])=>{const first=rs[0]||{};const opens=first.phuc_khao_tu?new Date(first.phuc_khao_tu):null;const closes=first.phuc_khao_den?new Date(first.phuc_khao_den):null;const now=new Date();const configured=!!(opens&&closes);const inWindow=configured&&now>=opens&&now<=closes;const windowText=!configured?'Chưa mở thời gian phúc khảo':now<opens?'Mở phúc khảo từ '+formatDateVN(opens.toISOString(),true):now>closes?'Đã hết hạn phúc khảo':'Hạn phúc khảo đến '+formatDateVN(closes.toISOString(),true);return `<div class="portal-result-card"><div class="portal-round-head"><h3>${esc(name)}</h3><span class="badge ${inWindow?'ok':'warn'}">${esc(windowText)}</span></div><div class="table-wrap sticky-table-wrap"><table class="table"><thead><tr><th>Môn</th><th>SBD</th><th>Trắc nghiệm</th><th>Tự luận</th><th>Điểm</th><th>Ngày kiểm tra</th><th>Ghi chú cập nhật</th>${isStudent?'<th>Phúc khảo trắc nghiệm</th><th>Phúc khảo tự luận</th>':''}</tr></thead><tbody>${rs.sort((a,b)=>subjects.indexOf(a.mon)-subjects.indexOf(b.mon)).map(r=>{const aps=appeals.filter(a=>Number(a.ket_qua_id)===Number(r.id));const cell=part=>{const ap=aps.find(a=>a.phan_kiem_tra===part);const score=part==='Trắc nghiệm'?r.diem_trac_nghiem:r.diem_tu_luan;if(score===null||score===undefined||score==='')return '<span class="muted">—</span>';if(!isStudent)return '<span class="muted">—</span>';if(ap)return `<span class="badge ${ap.trang_thai==='Đã xử lý'?'ok':'warn'}">${esc(ap.trang_thai||'Đã gửi')}</span>${ap.phan_hoi?`<small class="appeal-part-reply">${esc(ap.phan_hoi)}</small>`:''}${ap.anh_minh_chung_admin?'<small>Đã có minh chứng từ nhà trường</small>':''}`;if(!inWindow)return `<span class="muted">${esc(windowText)}</span>`;return `<label class="appeal-part-check"><input type="checkbox" class="appeal-part-toggle" data-id="${r.id}" data-part="${part}"><span>Đề nghị</span></label>`;};return `<tr><td>${esc(r.mon)}</td><td>${esc(r.so_bao_danh||'—')}</td><td>${r.diem_trac_nghiem==null?'—':Number(r.diem_trac_nghiem).toLocaleString('vi-VN')}</td><td>${r.diem_tu_luan==null?'—':Number(r.diem_tu_luan).toLocaleString('vi-VN')}</td><td><b class="score-value">${Number(r.diem).toLocaleString('vi-VN')}</b></td><td>${esc(formatDateVN(r.ngay_kiem_tra)||'—')}</td><td>${esc(r.ghi_chu||'—')}</td>${isStudent?`<td>${cell('Trắc nghiệm')}</td><td>${cell('Tự luận')}</td>`:''}</tr>`}).join('')}</tbody></table></div></div>`}).join('');
 el.querySelectorAll('.appeal-part-toggle').forEach(ch=>ch.onchange=async()=>{if(!ch.checked)return;const id=Number(ch.dataset.id),part=ch.dataset.part;ch.disabled=true;const msg=el.querySelector('#appealInlineMessage');msg.textContent='';const {data,error}=await supabase.rpc('portal_gui_phuc_khao_phan',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||'',p_ket_qua_id:id,p_phan:part});if(error||!data?.ok){ch.checked=false;ch.disabled=false;msg.textContent=error?.message||data?.message||'Không gửi được yêu cầu phúc khảo.';return;}toast('Đã gửi yêu cầu phúc khảo phần '+part+'.','ok');await init(el.closest('.portal-view'),user,()=>location.reload());});
 };
 el.querySelector('#resultRound').onchange=draw;draw();
}
function renderDiscipline(el,rows){
 const totalMinus=rows.reduce((a,x)=>a+Math.max(0,-Number(x.diem||0)),0);const totalPlus=rows.reduce((a,x)=>a+Math.max(0,Number(x.diem||0)),0);
 el.innerHTML=`<div class="portal-kpis"><div><small>Số lượt ghi nhận</small><b>${rows.length}</b></div><div><small>Tổng điểm cộng</small><b class="plus-text">+${totalPlus}</b></div><div><small>Tổng điểm trừ</small><b class="minus-text">−${totalMinus}</b></div><div><small>Điểm</small><b>${totalPlus-totalMinus}</b></div></div><h2>Chi tiết nề nếp & thi đua</h2>${rows.length?`<div class="table-wrap sticky-table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Buổi</th><th>Nội dung</th><th>Điểm</th><th>Người ghi nhận</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.ngay_diem_danh||'')}</td><td>${esc(x.buoi||'')}</td><td>${esc(x.chi_tiet||x.trang_thai||x.ma_hd||'')}</td><td class="${Number(x.diem)<0?'minus-text':'plus-text'}">${Number(x.diem)>0?'+':''}${Number(x.diem||0)}</td><td>${esc(x.ten_nguoi_cap_nhat||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Chưa có dữ liệu nề nếp trong hệ thống.</div>'}`;
}
function renderAppeals(el,results,appeals,user){
 const available=results.filter(r=>!appeals.some(a=>a.ket_qua_id===r.id));
 el.innerHTML=`<div class="portal-section-head"><div><h2>Yêu cầu phúc khảo bài kiểm tra</h2><p>Chọn bài kiểm tra có điểm và nêu rõ nội dung cần xem xét. Nhà trường sẽ cập nhật trạng thái xử lý tại đây.</p></div></div><div class="appeal-form"><label>Bài kiểm tra<select id="appealResult" required><option value="">-- Chọn đợt kiểm tra và môn --</option>${available.map(r=>`<option value="${r.id}">${esc(r.dot_kiem_tra)} · ${esc(r.mon)} · Điểm ${esc(r.diem)}</option>`).join('')}</select></label><label>Lý do phúc khảo<textarea id="appealReason" rows="4" placeholder="Nêu cụ thể nội dung đề nghị kiểm tra lại..." required></textarea></label><button id="appealSubmit" class="btn primary">Gửi yêu cầu phúc khảo</button><div id="appealMessage" class="error"></div></div><h3>Lịch sử yêu cầu</h3>${appeals.length?`<div class="table-wrap sticky-table-wrap"><table class="table"><thead><tr><th>Đợt kiểm tra</th><th>Môn</th><th>Lý do</th><th>Ngày gửi</th><th>Trạng thái</th><th>Phản hồi</th><th>Điểm hiện tại / ghi chú cập nhật</th></tr></thead><tbody>${appeals.map(a=>`<tr><td>${esc(a.dot_kiem_tra||'')}</td><td>${esc(a.mon||'')}</td><td>${esc(a.ly_do||'')}</td><td>${esc(a.created_at||'')}</td><td><span class="badge ${a.trang_thai==='Đã xử lý'?'ok':'warn'}">${esc(a.trang_thai||'Đã gửi')}</span></td><td>${esc(a.phan_hoi||'—')}</td><td>${esc(a.diem??'')}${a.ghi_chu_ket_qua?` · ${esc(a.ghi_chu_ket_qua)}`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Bạn chưa gửi yêu cầu phúc khảo nào.</div>'}`;
 el.querySelector('#appealSubmit').onclick=async()=>{const id=el.querySelector('#appealResult').value;const reason=el.querySelector('#appealReason').value.trim();const msg=el.querySelector('#appealMessage');msg.textContent='';if(!id||!reason){msg.textContent='Vui lòng chọn bài kiểm tra và nhập lý do.';return;}const {data,error}=await supabase.rpc('portal_gui_phuc_khao',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||'',p_ket_qua_id:Number(id),p_ly_do:reason});if(error||!data?.ok){msg.textContent=error?.message||data?.message||'Không gửi được yêu cầu. Hãy kiểm tra SQL migration 021.';return;}toast('Đã gửi yêu cầu phúc khảo.','ok');await init(el.closest('.portal-view'),user,()=>location.reload());document.querySelector('[data-tab="appeals"]')?.click();};
}
