import {supabase,appConfig} from './config.js';
import {esc,toast} from './ui.js';
const subjects=['Toán','Văn','Tiếng Anh','Vật lý','Hoá học','Sinh học','Lịch Sử','Địa lý','GD KTPL'];
export async function init(root,user,logout){
 const isStudent=user.portalRole==='student';
 root.innerHTML=`<header class="portal-top"><div><div class="portal-eyebrow">THPT Lê Hồng Phong · ${esc(appConfig.namHoc)}</div><h1>${isStudent?'Cổng thông tin học sinh':'Cổng thông tin phụ huynh'}</h1><p>Theo dõi kết quả học tập, kiểm tra và nề nếp</p></div><button id="portalLogout" class="btn light">Đăng xuất</button></header><div class="portal-content"><section class="portal-profile" id="portalProfile">Đang tải thông tin học sinh...</section><div class="portal-tabs"><button class="active" data-tab="results">📘 Kết quả kiểm tra</button><button data-tab="discipline">📋 Nề nếp & thi đua</button>${isStudent?'<button data-tab="appeals">✍️ Phúc khảo</button>':''}</div><section id="portal-results" class="portal-panel"></section><section id="portal-discipline" class="portal-panel hidden"></section>${isStudent?'<section id="portal-appeals" class="portal-panel hidden"></section>':''}</div>`;
 root.querySelector('#portalLogout').onclick=logout;
 root.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{root.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));root.querySelectorAll('.portal-panel').forEach(x=>x.classList.add('hidden'));root.querySelector('#portal-'+btn.dataset.tab).classList.remove('hidden');});
 const {data,error}=await supabase.rpc('portal_lay_du_lieu',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||''});
 if(error||!data){root.querySelector('#portalProfile').innerHTML=`<div class="danger-box">Không tải được dữ liệu: ${esc(error?.message||'Không tìm thấy tài khoản')}. Hãy chạy SQL migration 021.</div>`;return;}
 const student=data.hoc_sinh||{};const results=data.ket_qua||[];const attendance=data.ne_nep||[];const appeals=data.phuc_khao||[];
 root.querySelector('#portalProfile').innerHTML=`<div class="portal-avatar">🎓</div><div class="portal-student-meta"><h2>${esc(student.ho_ten||user.ho_ten)}</h2><p>Mã học sinh: <b>${esc(student.ma_hs||user.ma_hs)}</b> · Lớp <b>${esc(student.lop||'')}</b> · Khối ${esc(student.khoi||'')}</p></div><div class="portal-summary"><div><small>Bài kiểm tra có điểm</small><b>${results.length}</b></div><div><small>Lượt nề nếp</small><b>${attendance.length}</b></div>${isStudent?`<div><small>Yêu cầu phúc khảo</small><b>${appeals.length}</b></div>`:''}</div>`;
 renderResults(root.querySelector('#portal-results'),results,isStudent,appeals,user);
 renderDiscipline(root.querySelector('#portal-discipline'),attendance);
 if(isStudent)renderAppeals(root.querySelector('#portal-appeals'),results,appeals,user);
}
function renderResults(el,rows,isStudent,appeals,user){
 const rounds=[...new Set(rows.map(r=>r.dot_kiem_tra).filter(Boolean))];
 el.innerHTML=`<div class="portal-section-head"><div><h2>Kết quả kiểm tra, khảo sát</h2><p>Chỉ hiển thị những môn có điểm. Môn không có điểm được hiểu là chưa thi hoặc chưa có kết quả được đăng tải.</p></div><select id="resultRound"><option value="">Tất cả các đợt</option>${rounds.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div id="resultTable"></div>`;
 const draw=()=>{const round=el.querySelector('#resultRound').value;const list=rows.filter(x=>!round||x.dot_kiem_tra===round);if(!list.length){el.querySelector('#resultTable').innerHTML='<div class="empty">Chưa có kết quả kiểm tra được đăng tải.</div>';return;}const groups={};list.forEach(r=>(groups[r.dot_kiem_tra]??=[]).push(r));el.querySelector('#resultTable').innerHTML=Object.entries(groups).map(([name,rs])=>`<div class="portal-result-card"><h3>${esc(name)}</h3><div class="table-wrap sticky-table-wrap"><table class="table"><thead><tr><th>Môn</th><th>Điểm</th><th>Ngày kiểm tra</th><th>Loại</th><th>Phúc khảo</th></tr></thead><tbody>${rs.sort((a,b)=>subjects.indexOf(a.mon)-subjects.indexOf(b.mon)).map(r=>{const ap=appeals.find(a=>a.ket_qua_id===r.id);return `<tr><td>${esc(r.mon)}</td><td><b class="score-value">${Number(r.diem).toLocaleString('vi-VN')}</b></td><td>${esc(r.ngay_kiem_tra||'—')}</td><td>${esc(r.loai_kiem_tra||'')}</td><td>${isStudent?(ap?`<span class="badge ${ap.trang_thai==='Đã xử lý'?'ok':'warn'}">${esc(ap.trang_thai||'Đã gửi')}</span>`:`<button class="btn light appeal-shortcut" data-id="${r.id}">Yêu cầu phúc khảo</button>`):'—'}</td></tr>`}).join('')}</tbody></table></div></div>`).join('');el.querySelectorAll('.appeal-shortcut').forEach(btn=>btn.onclick=()=>{document.querySelector('[data-tab="appeals"]')?.click();document.querySelector('#appealResult').value=btn.dataset.id;document.querySelector('#appealReason').focus();});};el.querySelector('#resultRound').onchange=draw;draw();
}
function renderDiscipline(el,rows){
 const totalMinus=rows.reduce((a,x)=>a+Math.max(0,-Number(x.diem||0)),0);const totalPlus=rows.reduce((a,x)=>a+Math.max(0,Number(x.diem||0)),0);
 el.innerHTML=`<div class="portal-kpis"><div><small>Số lượt ghi nhận</small><b>${rows.length}</b></div><div><small>Tổng điểm cộng</small><b class="plus-text">+${totalPlus}</b></div><div><small>Tổng điểm trừ</small><b class="minus-text">−${totalMinus}</b></div><div><small>Điểm</small><b>${totalPlus-totalMinus}</b></div></div><h2>Chi tiết nề nếp & thi đua</h2>${rows.length?`<div class="table-wrap sticky-table-wrap"><table class="table"><thead><tr><th>Ngày</th><th>Buổi</th><th>Nội dung</th><th>Điểm</th><th>Người ghi nhận</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.ngay_diem_danh||'')}</td><td>${esc(x.buoi||'')}</td><td>${esc(x.chi_tiet||x.trang_thai||x.ma_hd||'')}</td><td class="${Number(x.diem)<0?'minus-text':'plus-text'}">${Number(x.diem)>0?'+':''}${Number(x.diem||0)}</td><td>${esc(x.ten_nguoi_cap_nhat||'')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Chưa có dữ liệu nề nếp trong hệ thống.</div>'}`;
}
function renderAppeals(el,results,appeals,user){
 const available=results.filter(r=>!appeals.some(a=>a.ket_qua_id===r.id));
 el.innerHTML=`<div class="portal-section-head"><div><h2>Yêu cầu phúc khảo bài kiểm tra</h2><p>Chọn bài kiểm tra có điểm và nêu rõ nội dung cần xem xét. Nhà trường sẽ cập nhật trạng thái xử lý tại đây.</p></div></div><div class="appeal-form"><label>Bài kiểm tra<select id="appealResult" required><option value="">-- Chọn đợt kiểm tra và môn --</option>${available.map(r=>`<option value="${r.id}">${esc(r.dot_kiem_tra)} · ${esc(r.mon)} · Điểm ${esc(r.diem)}</option>`).join('')}</select></label><label>Lý do phúc khảo<textarea id="appealReason" rows="4" placeholder="Nêu cụ thể nội dung đề nghị kiểm tra lại..." required></textarea></label><button id="appealSubmit" class="btn primary">Gửi yêu cầu phúc khảo</button><div id="appealMessage" class="error"></div></div><h3>Lịch sử yêu cầu</h3>${appeals.length?`<div class="table-wrap sticky-table-wrap"><table class="table"><thead><tr><th>Đợt kiểm tra</th><th>Môn</th><th>Lý do</th><th>Ngày gửi</th><th>Trạng thái</th><th>Phản hồi</th></tr></thead><tbody>${appeals.map(a=>`<tr><td>${esc(a.dot_kiem_tra||'')}</td><td>${esc(a.mon||'')}</td><td>${esc(a.ly_do||'')}</td><td>${esc(a.created_at||'')}</td><td><span class="badge ${a.trang_thai==='Đã xử lý'?'ok':'warn'}">${esc(a.trang_thai||'Đã gửi')}</span></td><td>${esc(a.phan_hoi||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Bạn chưa gửi yêu cầu phúc khảo nào.</div>'}`;
 el.querySelector('#appealSubmit').onclick=async()=>{const id=el.querySelector('#appealResult').value;const reason=el.querySelector('#appealReason').value.trim();const msg=el.querySelector('#appealMessage');msg.textContent='';if(!id||!reason){msg.textContent='Vui lòng chọn bài kiểm tra và nhập lý do.';return;}const {data,error}=await supabase.rpc('portal_gui_phuc_khao',{p_ma_hs:user.ma_hs,p_mat_khau:user.portalPassword||'',p_ket_qua_id:Number(id),p_ly_do:reason});if(error||!data?.ok){msg.textContent=error?.message||data?.message||'Không gửi được yêu cầu. Hãy kiểm tra SQL migration 021.';return;}toast('Đã gửi yêu cầu phúc khảo.','ok');await init(el.closest('.portal-view'),user,()=>location.reload());document.querySelector('[data-tab="appeals"]')?.click();};
}
