// js/quantri-tieuchi.js
import { supabase } from './config.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const el=id=>document.getElementById(id);let rows=[],editingId=null;
const groups=['Nề nếp','Học tập','Đoàn đội','Hoạt động tập thể'], types=['Điểm cộng','Điểm trừ'], targets=['Cá nhân','Tập thể'];
function render(){
 el('content-criteria').innerHTML=`<div class="panel-pad">
 <div class="filters grid grid-4"><div class="field"><label>Tìm tiêu chí</label><input id="tc_q" placeholder="Tên, mã..."></div><div class="field"><label>Mảng</label><select id="tc_group"><option value="">Tất cả</option>${groups.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Loại</label><select id="tc_type"><option value="">Tất cả</option>${types.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="actions"><button class="btn btn-primary" id="tc_add">+ Thêm tiêu chí</button></div></div>
 <div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Mã</th><th>Tên tiêu chí</th><th>Mảng</th><th>Đối tượng</th><th>Loại</th><th>Điểm</th><th>Thao tác</th></tr></thead><tbody id="ct_body"></tbody></table></div>
 </div>`;
 ['tc_q','tc_group','tc_type'].forEach(x=>el(x).oninput=filter);el('tc_add').onclick=()=>open();load();
}
async function load(){const {data,error}=await supabase.from('danh_muc_diem').select('*').order('mang').order('loai').order('ten_hd');if(error){window.ui.toast(error.message,'error');return}rows=data||[];filter()}
function filter(){const q=(el('tc_q')?.value||'').toLowerCase(),g=el('tc_group')?.value||'',t=el('tc_type')?.value||'';const a=rows.filter(r=>(!q||[r.ma_hd,r.ten_hd].some(v=>String(v||'').toLowerCase().includes(q)))&&(!g||r.mang===g)&&(!t||r.loai===t));el('ct_body').innerHTML=a.length?a.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.ma_hd)}</td><td><b>${esc(r.ten_hd)}</b></td><td>${esc(r.mang)}</td><td>${esc(r.doi_tuong||'Cá nhân')}</td><td><span class="badge ${r.loai==='Điểm trừ'?'badge-red':'badge-green'}">${esc(r.loai)}</span></td><td>${esc(r.diem)}</td><td><button class="btn btn-sm" data-edit="${r.id}">Sửa</button> <button class="btn btn-sm btn-danger" data-del="${r.id}">Xóa</button></td></tr>`).join(''):`<tr><td colspan="8" class="empty">Không có tiêu chí.</td></tr>`;el('ct_body').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(rows.find(x=>String(x.id)===b.dataset.edit)));el('ct_body').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(b.dataset.del))}
function open(r=null){editingId=r?.id||null;window.ui.modal.open(editingId?'Sửa tiêu chí':'Thêm tiêu chí',`<div class="grid grid-2"><div class="field"><label>Mã tiêu chí *</label><input id="ct_ma" value="${esc(r?.ma_hd)}"></div><div class="field"><label>Tên tiêu chí *</label><input id="ct_ten" value="${esc(r?.ten_hd)}"></div><div class="field"><label>Mảng</label><select id="ct_mang">${groups.map(x=>`<option ${r?.mang===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Đối tượng</label><select id="ct_doi">${targets.map(x=>`<option ${r?.doi_tuong===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Loại</label><select id="ct_loai">${types.map(x=>`<option ${r?.loai===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Điểm</label><input id="ct_diem" type="number" step="0.5" value="${r?.diem??1}"></div></div>`,`<button class="btn" id="ct_cancel">Hủy</button><button class="btn btn-primary" id="ct_save">Lưu</button>`);el('ct_cancel').onclick=window.ui.modal.close;el('ct_save').onclick=save}
async function save(){const d={ma_hd:el('ct_ma').value.trim(),ten_hd:el('ct_ten').value.trim(),mang:el('ct_mang').value,doi_tuong:el('ct_doi').value,loai:el('ct_loai').value,diem:+el('ct_diem').value};if(!d.ma_hd||!d.ten_hd)return window.ui.toast('Cần nhập mã và tên tiêu chí.','error');const {error}=editingId?await supabase.from('danh_muc_diem').update(d).eq('id',editingId):await supabase.from('danh_muc_diem').insert(d);if(error)return window.ui.toast(error.message,'error');window.ui.modal.close();window.ui.toast('Đã lưu tiêu chí.','success');load()}
async function remove(id){if(!confirm('Xóa tiêu chí này?'))return;const {error}=await supabase.from('danh_muc_diem').delete().eq('id',id);if(error)return window.ui.toast(error.message,'error');load()}
export function initCriteria(){render()}
