import {supabase} from './config.js?v=3.0.5.25.30';
import {esc,toast,modal,closeModal} from './ui.js?v=3.0.5.25.30';
import {Auth} from './auth.js?v=3.0.5.25.30';
export async function init(root){
 const u=Auth.currentUser;const cls=String(u?.lop_quan_ly||'').trim();
 root.innerHTML=`<div class="page-head"><div><h2>🔑 Cấp lại mật khẩu phụ huynh</h2><p>Chỉ hiển thị học sinh thuộc lớp chủ nhiệm của tài khoản đang đăng nhập.</p></div></div><div class="toolbar"><input id="rpSearch" placeholder="Tìm học sinh theo tên hoặc mã"><button id="rpReload" class="btn light">Tải lại</button></div><div id="rpNotice" class="notice">${cls?`Lớp chủ nhiệm: <b>${esc(cls)}</b>`:'Tài khoản chưa được gán lớp chủ nhiệm.'}</div><div id="rpTable"></div>`;
 const table=root.querySelector('#rpTable');if(!cls){table.innerHTML='<div class="danger-box">Không tìm thấy lớp chủ nhiệm. Liên hệ quản trị viên để cập nhật tài khoản.</div>';return;}
 async function load(){table.innerHTML='<div class="empty">Đang tải danh sách học sinh...</div>';const {data,error}=await supabase.rpc('gvcn_lay_hoc_sinh_reset_mat_khau',{p_ma_cb:u.ma_cb,p_mat_khau:u.credentialPassword||'',p_lop:cls});if(error){table.innerHTML=`<div class="danger-box">${esc(error.message)}<br>Hãy chạy migration 022_reset_mat_khau_phu_huynh_gvcn.sql.</div>`;return;}const rows=data?.rows||[];table.innerHTML=rows.length?`<div class="table-wrap" style="max-height:65vh;overflow:auto"><table class="table"><thead><tr><th>Mã HS</th><th>Họ tên</th><th>Lớp</th><th>Tài khoản PH/HS</th><th>Thao tác</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.ma_hs)}</td><td>${esc(s.ho_ten)}</td><td>${esc(s.lop)}</td><td>${s.has_password?'Đã có mật khẩu':'Chưa có mật khẩu'}</td><td><button class="btn light rp-reset" data-ma="${esc(s.ma_hs)}" data-name="${esc(s.ho_ten)}">Cấp lại mật khẩu</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Lớp chưa có học sinh hoặc không có quyền truy cập.';
 root.querySelectorAll('.rp-reset').forEach(btn=>btn.onclick=()=>reset(btn.dataset.ma,btn.dataset.name));}
 async function reset(ma,name){const m=modal('Cấp lại mật khẩu',`<p>Cấp mật khẩu mới cho tài khoản phụ huynh/học sinh của <b>${esc(name)}</b> (${esc(ma)}).</p><label>Mật khẩu mới<input id="rpNew" type="text" value="123456" autocomplete="off"></label><div class="scope-help">Nên cấp mật khẩu tạm thời và đề nghị phụ huynh đổi sau khi đăng nhập.</div>`,`<button id="rpCancel" class="btn light">Hủy</button><button id="rpSave" class="btn primary">Xác nhận cấp lại</button>`);m.querySelector('#rpCancel').onclick=closeModal;m.querySelector('#rpSave').onclick=async()=>{const pw=m.querySelector('#rpNew').value;if(pw.trim().length<6)return toast('Mật khẩu phải có ít nhất 6 ký tự.','err');const {data,error}=await supabase.rpc('gvcn_reset_mat_khau_phu_huynh',{p_ma_cb:u.ma_cb,p_mat_khau:u.credentialPassword||'',p_ma_hs:ma,p_lop:cls,p_mat_khau_moi:pw});if(error)return toast(error.message,'err');if(!data?.ok)return toast(data?.message||'Không thể cấp lại mật khẩu.','err');closeModal();toast('Đã cấp lại mật khẩu cho '+name+'.','ok');load();}
 }
 root.querySelector('#rpSearch').oninput=()=>root.querySelectorAll('#rpTable tbody tr').forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(root.querySelector('#rpSearch').value.toLowerCase())?'':'none');root.querySelector('#rpReload').onclick=load;await load();
}
