import {supabase} from './config.js?v=3.0.5.25.25';
import {Auth} from './auth.js?v=3.0.5.25.25';
import {esc,toast} from './ui.js?v=3.0.5.25.25';
export async function init(root){
 const u=Auth.currentUser||{};const role=String(u.vai_tro||'').toLowerCase();const roles=Array.isArray(u.vai_tro_list)?u.vai_tro_list.map(x=>String(x).toLowerCase()):[];const admin=role==='admin'||role==='quản trị hệ thống'||roles.includes('admin');const gvcn=role.includes('gvcn')||role.includes('chủ nhiệm')||roles.some(x=>x.includes('gvcn')||x.includes('chủ nhiệm'));if(!admin&&!gvcn){root.innerHTML='<div class="danger-box">Chỉ Admin hoặc giáo viên chủ nhiệm được gửi thông báo.</div>';return;}
 const cls=String(u.lop_quan_ly||'');const {data:students,error}=await supabase.from('danh_sach').select('ma_hs,ho_ten,khoi,lop,trang_thai').order('lop').order('ho_ten').limit(3000);if(error){root.innerHTML=`<div class="danger-box">${esc(error.message)}</div>`;return;}const classes=[...new Set((students||[]).map(x=>x.lop).filter(Boolean))].sort();
 root.innerHTML=`<div class="page-head"><div><h2>📢 Thông báo đến phụ huynh / học sinh</h2><p>Gửi thông báo có thể xuất hiện dạng popup, thanh chạy ngang và lưu trong danh sách thông báo.</p></div></div><div class="action-card"><div class="grid"><label>Tiêu đề<input id="ntTitle" maxlength="160" placeholder="Ví dụ: Lịch kiểm tra khảo sát tuần tới"></label><label>Phạm vi<select id="ntScope">${admin?'<option value="Toàn trường">Toàn trường</option>':''}<option value="Lớp">Lớp</option><option value="Học sinh">Học sinh</option></select></label><label id="ntTargetLabel">Lớp nhận thông báo<select id="ntTarget">${classes.filter(x=>admin||x===cls).map(x=>`<option value="${esc(x)}" ${x===cls?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label style="grid-column:1/-1">Nội dung<textarea id="ntBody" rows="5" placeholder="Nội dung cần học sinh/phụ huynh nắm bắt và thực hiện"></textarea></label></div><div class="check-grid" style="margin:12px 0"><label class="check-item"><input id="ntPopup" type="checkbox" checked> Popup khi đăng nhập nếu chưa đọc</label><label class="check-item"><input id="ntTicker" type="checkbox" checked> Hiển thị trên thanh chạy ngang</label></div><button id="ntSend" class="btn primary">📢 Gửi thông báo</button><div id="ntResult"></div></div>`;
 const scope=root.querySelector('#ntScope'),label=root.querySelector('#ntTargetLabel');const fill=()=>{if(scope.value==='Toàn trường'){label.innerHTML='<span class="muted">Thông báo đến toàn bộ học sinh đang học.</span>';return;}if(scope.value==='Lớp'){label.innerHTML=`<label>Lớp nhận thông báo<select id="ntTarget">${classes.filter(x=>admin||x===cls).map(x=>`<option value="${esc(x)}" ${x===cls?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;return;}label.innerHTML=`<label>Học sinh nhận thông báo<select id="ntTarget">${students.filter(x=>(admin||x.lop===cls)&&!['inactive','nghi hoc','đã nghỉ'].includes(String(x.trang_thai||'').toLowerCase())).map(x=>`<option value="${esc(x.ma_hs)}">${esc(x.ho_ten)} — ${esc(x.lop)} (${esc(x.ma_hs)})</option>`).join('')}</select></label>`;};scope.onchange=fill;
 root.querySelector('#ntSend').onclick=async()=>{const title=root.querySelector('#ntTitle').value.trim(),body=root.querySelector('#ntBody').value.trim(),s=scope.value,target=s==='Toàn trường'?'':root.querySelector('#ntTarget')?.value||'';if(title.length<3||body.length<3)return toast('Nhập tiêu đề và nội dung thông báo.','err');if(s!=='Toàn trường'&&!target)return toast('Chọn lớp hoặc học sinh nhận thông báo.','err');if(!confirm(`Gửi thông báo đến ${s==='Toàn trường'?'toàn trường':s==='Lớp'?'lớp '+target:'học sinh '+target}?`))return;const {data,error}=await supabase.rpc('admin_gui_thong_bao',{p_ma_cb:u.ma_cb,p_mat_khau:u.credentialPassword||'',p_tieu_de:title,p_noi_dung:body,p_pham_vi:s,p_lop:target,p_popup:root.querySelector('#ntPopup').checked,p_ticker:root.querySelector('#ntTicker').checked});if(error||!data?.ok)return toast(error?.message||data?.message||'Không gửi được. Hãy chạy SQL 023.','err');root.querySelector('#ntResult').innerHTML=`<div class="notice">Đã gửi thông báo đến <b>${data.count}</b> học sinh.</div>`;toast('Đã gửi thông báo.','ok');};
}
