-- V3.0.5.5 - nền tảng Sổ đầu bài / điểm theo tiết và tuần.
-- Không xóa hoặc sửa dữ liệu lịch sử hiện có.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='diem_danh_master' AND column_name='tuan_hoc'
  ) THEN ALTER TABLE public.diem_danh_master ADD COLUMN tuan_hoc integer; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='diem_danh_master' AND column_name='tiet'
  ) THEN ALTER TABLE public.diem_danh_master ADD COLUMN tiet integer; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='diem_danh_master' AND column_name='mon_hoc'
  ) THEN ALTER TABLE public.diem_danh_master ADD COLUMN mon_hoc text; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='diem_danh_master' AND column_name='nguon_cham'
  ) THEN ALTER TABLE public.diem_danh_master ADD COLUMN nguon_cham text; END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_diem_master_tuan_lop_tiet
ON public.diem_danh_master(nam_hoc, tuan_hoc, lop, tiet);

-- Bảng đăng ký Tuần học tốt của GVCN.
CREATE TABLE IF NOT EXISTS public.tuan_hoc_tot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  tuan_hoc integer NOT NULL,
  lop varchar NOT NULL,
  ma_cb varchar,
  ten_cb text,
  trang_thai text NOT NULL DEFAULT 'Đăng ký',
  ghi_chu text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tuan_hoc_tot_lop_tuan
ON public.tuan_hoc_tot(nam_hoc,tuan_hoc,lop);

-- Kiểm tra cấu trúc.
SELECT column_name,data_type
FROM information_schema.columns
WHERE table_schema='public' AND table_name IN ('diem_danh_master','tuan_hoc_tot')
ORDER BY table_name,ordinal_position;
