-- V3.0.5.6
-- Sửa lỗi schema nam_hoc; bổ sung năm học, lịch học và sổ theo dõi báo vắng.
-- An toàn khi chạy trên CSDL đã tồn tại.

-- 1) diem_danh_master: đảm bảo có năm học để không lỗi index/thống kê.
ALTER TABLE public.diem_danh_master
  ADD COLUMN IF NOT EXISTS nam_hoc text;
UPDATE public.diem_danh_master
SET nam_hoc='2026-2027'
WHERE nam_hoc IS NULL OR btrim(nam_hoc)='';

CREATE INDEX IF NOT EXISTS idx_diem_master_namhoc_lop_ngay
ON public.diem_danh_master(nam_hoc,lop,ngay_diem_danh);

-- 2) tuan_hoc_tot: nếu bảng đã được tạo từ phiên bản cũ nhưng thiếu nam_hoc,
-- ALTER TABLE sẽ bổ sung thay vì CREATE IF NOT EXISTS bị bỏ qua.
CREATE TABLE IF NOT EXISTS public.tuan_hoc_tot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  tuan_hoc integer NOT NULL,
  lop varchar NOT NULL,
  ma_cb varchar,
  ten_cb text,
  trang_thai text NOT NULL DEFAULT 'Đăng ký',
  ghi_chu text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS nam_hoc text;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS tuan_hoc integer;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS lop varchar;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS ma_cb varchar;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS ten_cb text;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS trang_thai text;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS ghi_chu text;
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.tuan_hoc_tot ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
UPDATE public.tuan_hoc_tot SET nam_hoc='2026-2027' WHERE nam_hoc IS NULL OR btrim(nam_hoc)='';
CREATE UNIQUE INDEX IF NOT EXISTS uq_tuan_hoc_tot_lop_tuan ON public.tuan_hoc_tot(nam_hoc,tuan_hoc,lop);

-- 3) Bảng TKB tối thiểu để xác định lớp có học trong ngày.
CREATE TABLE IF NOT EXISTS public.thoi_khoa_bieu (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  thu integer NOT NULL CHECK (thu BETWEEN 2 AND 8),
  tiet integer NOT NULL,
  khoi varchar,
  lop varchar NOT NULL,
  mon_hoc text,
  ma_gv varchar,
  ten_gv text,
  buoi varchar,
  trang_thai text NOT NULL DEFAULT 'Hoạt động',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tkb_namhoc_thu_lop ON public.thoi_khoa_bieu(nam_hoc,thu,lop);

-- 4) Một bản ghi bắt buộc cho MỖI lớp phải báo vắng, kể cả so_vang=0.
CREATE TABLE IF NOT EXISTS public.bao_vang_lop (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  ngay_bao date NOT NULL,
  buoi varchar NOT NULL,
  khoi varchar,
  lop varchar NOT NULL,
  so_vang integer NOT NULL DEFAULT 0 CHECK (so_vang>=0),
  ma_cb varchar,
  ten_cb text,
  trang_thai text NOT NULL DEFAULT 'Đã báo',
  ghi_chu text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS nam_hoc text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ngay_bao date;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS buoi varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS khoi varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS lop varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS so_vang integer DEFAULT 0;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ma_cb varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ten_cb text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS trang_thai text DEFAULT 'Đã báo';
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ghi_chu text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
UPDATE public.bao_vang_lop SET nam_hoc='2026-2027' WHERE nam_hoc IS NULL OR btrim(nam_hoc)='';
UPDATE public.bao_vang_lop SET so_vang=0 WHERE so_vang IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_bao_vang_lop_ngay_buoi ON public.bao_vang_lop(nam_hoc,ngay_bao,buoi,lop);
CREATE INDEX IF NOT EXISTS idx_bao_vang_lop_date ON public.bao_vang_lop(nam_hoc,ngay_bao,buoi);

-- 5) Kiểm tra cuối cùng.
SELECT table_name,column_name,data_type
FROM information_schema.columns
WHERE table_schema='public'
  AND table_name IN ('diem_danh_master','tuan_hoc_tot','thoi_khoa_bieu','bao_vang_lop')
ORDER BY table_name,ordinal_position;
