-- V3.0.5.8
-- Sửa lỗi PostgREST: schema cache không thấy nam_hoc / bao_vang_lop.
-- Chạy toàn bộ file này trong Supabase SQL Editor của ĐÚNG project đang dùng bởi config.js.

BEGIN;

-- 1. diem_danh_master: bổ sung năm học nếu CSDL cũ chưa có.
ALTER TABLE public.diem_danh_master
  ADD COLUMN IF NOT EXISTS nam_hoc text;

UPDATE public.diem_danh_master
SET nam_hoc = '2026-2027'
WHERE nam_hoc IS NULL OR btrim(nam_hoc) = '';

CREATE INDEX IF NOT EXISTS idx_diem_master_namhoc_lop_ngay
  ON public.diem_danh_master(nam_hoc, lop, ngay_diem_danh);

-- 2. Bảng theo dõi lớp đã báo/chưa báo.
CREATE TABLE IF NOT EXISTS public.bao_vang_lop (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  ngay_bao date NOT NULL,
  buoi varchar NOT NULL,
  khoi varchar,
  lop varchar NOT NULL,
  so_vang integer NOT NULL DEFAULT 0 CHECK (so_vang >= 0),
  ma_cb varchar,
  ten_cb text,
  trang_thai text NOT NULL DEFAULT 'Đã báo',
  ghi_chu text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS nam_hoc text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ngay_bao date;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS buoi varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS khoi varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS lop varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS so_vang integer DEFAULT 0;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ma_cb varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ten_cb text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS trang_thai text DEFAULT 'Đã báo';
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ghi_chu text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE public.bao_vang_lop
SET nam_hoc = '2026-2027'
WHERE nam_hoc IS NULL OR btrim(nam_hoc) = '';

UPDATE public.bao_vang_lop
SET so_vang = 0
WHERE so_vang IS NULL;

CREATE INDEX IF NOT EXISTS idx_bao_vang_lop_date
  ON public.bao_vang_lop(nam_hoc, ngay_bao, buoi);

-- Chỉ tạo unique index khi chưa tồn tại. Nếu dữ liệu cũ có bản ghi trùng,
-- câu lệnh này sẽ báo lỗi để xử lý dữ liệu trùng thay vì âm thầm mất bản ghi.
CREATE UNIQUE INDEX IF NOT EXISTS uq_bao_vang_lop_ngay_buoi
  ON public.bao_vang_lop(nam_hoc, ngay_bao, buoi, lop);

-- 3. TKB tối thiểu, nếu chưa có.
CREATE TABLE IF NOT EXISTS public.thoi_khoa_bieu (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  thu integer NOT NULL CHECK (thu BETWEEN 2 AND 8),
  tiet integer NOT NULL,
  khoi varchar,
  lop varchar NOT NULL,
  mon_hoc text,
  ma_gv varchar,
  ten_gv text,
  buoi varchar,
  trang_thai text NOT NULL DEFAULT 'Hoạt động',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS nam_hoc text;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS thu integer;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS tiet integer;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS khoi varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS lop varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS mon_hoc text;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS ma_gv varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS ten_gv text;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS buoi varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS trang_thai text DEFAULT 'Hoạt động';
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE public.thoi_khoa_bieu
SET nam_hoc = '2026-2027'
WHERE nam_hoc IS NULL OR btrim(nam_hoc) = '';

CREATE INDEX IF NOT EXISTS idx_tkb_namhoc_thu_lop
  ON public.thoi_khoa_bieu(nam_hoc, thu, lop);

COMMIT;

-- 4. Buộc PostgREST nạp lại schema cache ngay sau migration.
NOTIFY pgrst, 'reload schema';

-- 5. Kiểm tra bắt buộc: kết quả phải có 2 bảng và các cột tương ứng.
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND (
    (table_name = 'diem_danh_master' AND column_name = 'nam_hoc')
    OR (table_name = 'bao_vang_lop' AND column_name IN ('nam_hoc','ngay_bao','buoi','khoi','lop','so_vang'))
    OR (table_name = 'thoi_khoa_bieu' AND column_name IN ('nam_hoc','thu','tiet','lop','buoi'))
  )
ORDER BY table_name, ordinal_position;
