-- V3.0.5.10
-- Đảm bảo TKB hoạt động ổn định và PostgREST thấy đầy đủ schema.
BEGIN;

CREATE TABLE IF NOT EXISTS public.thoi_khoa_bieu (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  thu integer NOT NULL CHECK (thu BETWEEN 2 AND 8),
  tiet integer NOT NULL,
  khoi varchar,
  lop varchar NOT NULL,
  mon_hoc text,
  ma_gv varchar,
  ten_gv text,
  buoi varchar,
  trang_thai text NOT NULL DEFAULT 'Hoạt động',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS nam_hoc text;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS thu integer;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS tiet integer;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS khoi varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS lop varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS mon_hoc text;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS ma_gv varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS ten_gv text;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS buoi varchar;
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS trang_thai text DEFAULT 'Hoạt động';
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.thoi_khoa_bieu ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE public.thoi_khoa_bieu SET nam_hoc='2026-2027'
WHERE nam_hoc IS NULL OR btrim(nam_hoc)='';

CREATE INDEX IF NOT EXISTS idx_tkb_namhoc_thu_buoi_lop
ON public.thoi_khoa_bieu(nam_hoc,thu,buoi,lop);

NOTIFY pgrst, 'reload schema';

SELECT table_name,column_name,data_type
FROM information_schema.columns
WHERE table_schema='public' AND table_name='thoi_khoa_bieu'
ORDER BY ordinal_position;
