-- V3.0.5.20 - Chuẩn hóa CSDL để kích hoạt Báo Vắng
-- Tương thích với cấu trúc hiện có và không bắt frontend phụ thuộc vào diem_danh_master.nam_hoc.
BEGIN;

-- 1. diem_danh_master: giữ nam_hoc là cột tùy chọn để các báo cáo mới có thể dùng,
-- nhưng frontend V3.0.5.20 không bắt buộc phải gửi cột này khi ghi.
ALTER TABLE public.diem_danh_master
  ADD COLUMN IF NOT EXISTS nam_hoc text;

CREATE INDEX IF NOT EXISTS idx_diem_danh_master_namhoc_lop_ngay
  ON public.diem_danh_master(nam_hoc, lop, ngay_diem_danh);

-- 2. Bảng theo dõi lớp đã báo/chưa báo.
CREATE TABLE IF NOT EXISTS public.bao_vang_lop (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  ngay_bao date NOT NULL,
  buoi varchar NOT NULL,
  khoi varchar,
  lop varchar NOT NULL,
  so_vang integer NOT NULL DEFAULT 0 CHECK (so_vang >= 0),
  ma_cb varchar,
  ten_cb text,
  trang_thai text NOT NULL DEFAULT 'Đã báo',
  ghi_chu text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS nam_hoc text DEFAULT '2026-2027';
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ngay_bao date;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS buoi varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS khoi varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS lop varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS so_vang integer DEFAULT 0;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ma_cb varchar;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ten_cb text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS trang_thai text DEFAULT 'Đã báo';
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS ghi_chu text;
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.bao_vang_lop ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE public.bao_vang_lop SET nam_hoc='2026-2027' WHERE nam_hoc IS NULL OR btrim(nam_hoc)='';
UPDATE public.bao_vang_lop SET so_vang=0 WHERE so_vang IS NULL;
UPDATE public.bao_vang_lop SET trang_thai='Đã báo' WHERE trang_thai IS NULL OR btrim(trang_thai)='';
UPDATE public.bao_vang_lop SET updated_at=COALESCE(updated_at,now()) WHERE updated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_bao_vang_lop_date
  ON public.bao_vang_lop(nam_hoc, ngay_bao, buoi);

-- Xử lý bản ghi trùng trước khi tạo khóa duy nhất dùng cho các báo cáo sau này.
WITH ranked AS (
  SELECT id,
         row_number() OVER (
           PARTITION BY nam_hoc, ngay_bao, buoi, lop
           ORDER BY updated_at DESC NULLS LAST, id DESC
         ) AS rn
  FROM public.bao_vang_lop
  WHERE nam_hoc IS NOT NULL AND ngay_bao IS NOT NULL AND buoi IS NOT NULL AND lop IS NOT NULL
)
DELETE FROM public.bao_vang_lop b
USING ranked r
WHERE b.id=r.id AND r.rn>1;

CREATE UNIQUE INDEX IF NOT EXISTS uq_bao_vang_lop_namhoc_ngay_buoi_lop
  ON public.bao_vang_lop(nam_hoc, ngay_bao, buoi, lop);

-- 3. TKB tối giản: tiết và lớp có thể NULL vì lịch có thể áp dụng theo khối/toàn trường.
ALTER TABLE public.thoi_khoa_bieu ALTER COLUMN tiet DROP NOT NULL;
ALTER TABLE public.thoi_khoa_bieu ALTER COLUMN lop DROP NOT NULL;

-- 4. Quyền CRUD cần thiết cho ứng dụng frontend đang dùng Supabase anon key.
GRANT SELECT, INSERT, UPDATE ON public.diem_danh_master TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.bao_vang_lop TO anon, authenticated;
GRANT SELECT ON public.danh_sach TO anon, authenticated;
GRANT SELECT ON public.thoi_khoa_bieu TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';

-- Kiểm tra sau khi chạy:
SELECT table_name, column_name, is_nullable, data_type
FROM information_schema.columns
WHERE table_schema='public'
  AND (
    (table_name='diem_danh_master' AND column_name IN ('ma_hs','ngay_diem_danh','buoi','trang_thai','ma_nguoi_cap_nhat','ten_nguoi_cap_nhat','nam_hoc'))
    OR (table_name='bao_vang_lop' AND column_name IN ('nam_hoc','ngay_bao','buoi','khoi','lop','so_vang','ma_cb','ten_cb','trang_thai'))
    OR (table_name='thoi_khoa_bieu' AND column_name IN ('nam_hoc','thu','tiet','khoi','lop','buoi','trang_thai'))
  )
ORDER BY table_name, ordinal_position;
