-- V3.0.5.25.8 - Lưu phân bố điểm theo tuần cho Cán bộ lớp.
-- Dùng cho Sổ đầu bài và điểm học sinh 0-10; không xóa dữ liệu cũ.
CREATE TABLE IF NOT EXISTS public.diem_hoc_tap_tuan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nam_hoc text NOT NULL DEFAULT '2026-2027',
  tuan_hoc integer NOT NULL,
  lop varchar NOT NULL,
  ma_hs varchar,
  ho_ten text,
  loai_diem text NOT NULL,
  diem smallint NOT NULL,
  so_luong integer NOT NULL DEFAULT 0,
  ma_nguoi_cap_nhat varchar,
  ten_nguoi_cap_nhat text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_diem_hoc_tap_tuan_loai CHECK (loai_diem IN ('SoDauBai','HocSinh')),
  CONSTRAINT chk_diem_hoc_tap_tuan_diem CHECK (diem BETWEEN 0 AND 10),
  CONSTRAINT chk_diem_hoc_tap_tuan_so_luong CHECK (so_luong >= 0),
  CONSTRAINT chk_diem_hoc_tap_tuan_hs CHECK ((loai_diem='SoDauBai' AND ma_hs IS NULL) OR (loai_diem='HocSinh' AND ma_hs IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_diem_hoc_tap_tuan_lop ON public.diem_hoc_tap_tuan(nam_hoc,tuan_hoc,lop,loai_diem);
CREATE INDEX IF NOT EXISTS idx_diem_hoc_tap_tuan_hs ON public.diem_hoc_tap_tuan(nam_hoc,tuan_hoc,ma_hs);
