-- V3.0.5.25.23: Cổng phụ huynh/học sinh, kết quả kiểm tra và phúc khảo.
-- Chạy một lần trên Supabase SQL Editor của đúng project.

-- Tài khoản phụ huynh/học sinh dùng danh_sach.ma_hs + danh_sach.mat_khau.
update public.danh_sach set mat_khau='123456' where mat_khau is null or btrim(mat_khau)='';

create table if not exists public.ket_qua_kiem_tra (
 id bigint generated by default as identity primary key,
 ma_hs varchar not null,
 nam_hoc text not null default '2026-2027',
 dot_kiem_tra text not null,
 loai_kiem_tra text not null default 'Định kỳ',
 mon text not null check (mon in ('Toán','Văn','Tiếng Anh','Vật lý','Hoá học','Sinh học','Lịch Sử','Địa lý','GD KTPL','Tin học')),
 diem numeric(4,2) not null check (diem>=0 and diem<=10),
 ngay_kiem_tra date,
 ghi_chu text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(ma_hs,dot_kiem_tra,mon,nam_hoc)
);
create index if not exists idx_ket_qua_kiem_tra_ma_hs on public.ket_qua_kiem_tra(ma_hs,nam_hoc,dot_kiem_tra);

create table if not exists public.phuc_khao_kiem_tra (
 id bigint generated by default as identity primary key,
 ket_qua_id bigint not null references public.ket_qua_kiem_tra(id) on delete cascade,
 ma_hs varchar not null,
 ly_do text not null,
 trang_thai text not null default 'Đã gửi' check (trang_thai in ('Đã gửi','Đang xem xét','Đã xử lý','Từ chối')),
 phan_hoi text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(ket_qua_id)
);
create index if not exists idx_phuc_khao_ma_hs on public.phuc_khao_kiem_tra(ma_hs,created_at desc);

create or replace function public.login_hoc_sinh(p_ma_hs text,p_mat_khau text,p_vai_tro text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.danh_sach%rowtype;
begin
 if p_vai_tro not in ('parent','student') then return null; end if;
 select * into s from public.danh_sach d where btrim(d.ma_hs)=btrim(p_ma_hs) and btrim(coalesce(d.mat_khau,''))=btrim(coalesce(p_mat_khau,'')) and (d.trang_thai is null or lower(btrim(d.trang_thai)) not in ('inactive','nghi hoc','đã nghỉ','false','0')) limit 1;
 if not found then return null; end if;
 return jsonb_build_object('ma_hs',s.ma_hs,'ho_ten',s.ho_ten,'khoi',s.khoi,'lop',s.lop,'nam_hoc',s.nam_hoc);
end $$;

create or replace function public.portal_lay_du_lieu(p_ma_hs text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.danh_sach%rowtype; r jsonb; n jsonb; a jsonb;
begin
 select * into s from public.danh_sach d where btrim(d.ma_hs)=btrim(p_ma_hs) and btrim(coalesce(d.mat_khau,''))=btrim(coalesce(p_mat_khau,'')) and (d.trang_thai is null or lower(btrim(d.trang_thai)) not in ('inactive','nghi hoc','đã nghỉ','false','0')) limit 1;
 if not found then return null; end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.dot_kiem_tra desc,x.mon), '[]'::jsonb) into r from public.ket_qua_kiem_tra x where x.ma_hs=s.ma_hs;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.ngay_diem_danh desc), '[]'::jsonb) into n from public.diem_danh_master x where x.ma_hs=s.ma_hs;
 select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('mon',q.mon,'dot_kiem_tra',q.dot_kiem_tra) order by p.created_at desc), '[]'::jsonb) into a from public.phuc_khao_kiem_tra p join public.ket_qua_kiem_tra q on q.id=p.ket_qua_id where p.ma_hs=s.ma_hs;
 return jsonb_build_object('hoc_sinh',jsonb_build_object('ma_hs',s.ma_hs,'ho_ten',s.ho_ten,'khoi',s.khoi,'lop',s.lop),'ket_qua',r,'ne_nep',n,'phuc_khao',a);
end $$;

create or replace function public.portal_gui_phuc_khao(p_ma_hs text,p_mat_khau text,p_ket_qua_id bigint,p_ly_do text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.danh_sach%rowtype; q public.ket_qua_kiem_tra%rowtype; new_id bigint;
begin
 select * into s from public.danh_sach d where btrim(d.ma_hs)=btrim(p_ma_hs) and btrim(coalesce(d.mat_khau,''))=btrim(coalesce(p_mat_khau,'')) and (d.trang_thai is null or lower(btrim(d.trang_thai)) not in ('inactive','nghi hoc','đã nghỉ','false','0')) limit 1;
 if not found then return jsonb_build_object('ok',false,'message','Tài khoản không hợp lệ.'); end if;
 select * into q from public.ket_qua_kiem_tra where id=p_ket_qua_id and ma_hs=s.ma_hs;
 if not found then return jsonb_build_object('ok',false,'message','Bài kiểm tra không thuộc tài khoản này.'); end if;
 if length(btrim(coalesce(p_ly_do,'')))<5 then return jsonb_build_object('ok',false,'message','Lý do phúc khảo cần ít nhất 5 ký tự.'); end if;
 insert into public.phuc_khao_kiem_tra(ket_qua_id,ma_hs,ly_do) values(q.id,s.ma_hs,btrim(p_ly_do)) returning id into new_id;
 return jsonb_build_object('ok',true,'id',new_id);
exception when unique_violation then return jsonb_build_object('ok',false,'message','Bài kiểm tra này đã có yêu cầu phúc khảo.');
end $$;

grant execute on function public.login_hoc_sinh(text,text,text) to anon, authenticated;
grant execute on function public.portal_lay_du_lieu(text,text) to anon, authenticated;
grant execute on function public.portal_gui_phuc_khao(text,text,bigint,text) to anon, authenticated;
-- Bật RLS nhưng KHÔNG cấp quyền REST trực tiếp cho anon; thao tác quản trị đi qua RPC xác thực cán bộ Admin.
alter table public.ket_qua_kiem_tra enable row level security;
alter table public.phuc_khao_kiem_tra enable row level security;
revoke all on public.ket_qua_kiem_tra from anon,authenticated;
revoke all on public.phuc_khao_kiem_tra from anon,authenticated;

create or replace function public.qlnn_xac_nhan_admin(p_ma_cb text,p_mat_khau text)
returns boolean language sql security definer set search_path=public as $$
 select exists(select 1 from public.can_bo c where btrim(c.ma_cb)=btrim(p_ma_cb) and coalesce(c.mat_khau,'')=coalesce(p_mat_khau,'') and coalesce(c.trang_thai,true)=true and (lower(coalesce(c.vai_tro,'')) in ('admin','quản trị hệ thống') or coalesce(c.vai_tro_list,'{}'::text[]) @> array['Admin']::text[]));
$$;
create or replace function public.admin_nhap_ket_qua(p_ma_cb text,p_mat_khau text,p_rows jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare item jsonb; n int:=0; hs text; monv text; diemv numeric; roundv text;
begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Chỉ quản trị hệ thống mới được đăng tải kết quả.'); end if;
 if jsonb_typeof(p_rows)<>'array' then return jsonb_build_object('ok',false,'message','Dữ liệu tải lên không hợp lệ.'); end if;
 for item in select * from jsonb_array_elements(p_rows) loop
  hs:=nullif(btrim(item->>'ma_hs'),''); monv:=btrim(item->>'mon'); roundv:=nullif(btrim(item->>'dot_kiem_tra'),''); diemv:=nullif(item->>'diem','')::numeric;
  if hs is null or roundv is null or monv not in ('Toán','Văn','Tiếng Anh','Vật lý','Hoá học','Sinh học','Lịch Sử','Địa lý','GD KTPL','Tin học') or diemv is null or diemv<0 or diemv>10 then continue; end if;
  if not exists(select 1 from public.danh_sach d where d.ma_hs=hs) then continue; end if;
  insert into public.ket_qua_kiem_tra(ma_hs,nam_hoc,dot_kiem_tra,loai_kiem_tra,mon,diem,ngay_kiem_tra,ghi_chu)
  values(hs,coalesce(nullif(item->>'nam_hoc',''),'2026-2027'),roundv,coalesce(nullif(item->>'loai_kiem_tra',''),'Định kỳ'),monv,diemv,nullif(item->>'ngay_kiem_tra','')::date,nullif(item->>'ghi_chu',''))
  on conflict(ma_hs,dot_kiem_tra,mon,nam_hoc) do update set loai_kiem_tra=excluded.loai_kiem_tra,diem=excluded.diem,ngay_kiem_tra=excluded.ngay_kiem_tra,ghi_chu=excluded.ghi_chu,updated_at=now(); n:=n+1;
 end loop;
 return jsonb_build_object('ok',true,'count',n);
exception when others then return jsonb_build_object('ok',false,'message','Lỗi nhập kết quả: '||sqlerrm);
end $$;
create or replace function public.admin_lay_ket_qua(p_ma_cb text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare r jsonb; begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.dot_kiem_tra desc,x.ma_hs,x.mon),'[]'::jsonb) into r from (select ma_hs,dot_kiem_tra,mon,diem,ngay_kiem_tra,loai_kiem_tra from public.ket_qua_kiem_tra order by dot_kiem_tra desc limit 1000) x;
 return jsonb_build_object('ok',true,'rows',r); end $$;
create or replace function public.admin_lay_phuc_khao(p_ma_cb text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare r jsonb; begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into r from (select p.id,p.ket_qua_id,p.ma_hs,p.ly_do,p.trang_thai,p.phan_hoi,p.created_at,q.mon,q.dot_kiem_tra,q.diem,q.id as ket_result_id from public.phuc_khao_kiem_tra p join public.ket_qua_kiem_tra q on q.id=p.ket_qua_id order by p.created_at desc limit 1000) x;
 return jsonb_build_object('ok',true,'rows',r); end $$;
create or replace function public.admin_cap_nhat_phuc_khao(p_ma_cb text,p_mat_khau text,p_id bigint,p_trang_thai text,p_phan_hoi text)
returns jsonb language plpgsql security definer set search_path=public as $$ begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 if p_trang_thai not in ('Đã gửi','Đang xem xét','Đã xử lý','Từ chối') then return jsonb_build_object('ok',false,'message','Trạng thái không hợp lệ.'); end if;
 update public.phuc_khao_kiem_tra set trang_thai=p_trang_thai,phan_hoi=nullif(btrim(p_phan_hoi),''),updated_at=now() where id=p_id;
 if not found then return jsonb_build_object('ok',false,'message','Không tìm thấy yêu cầu phúc khảo.'); end if;
 return jsonb_build_object('ok',true); end $$;

grant execute on function public.login_hoc_sinh(text,text,text) to anon, authenticated;
grant execute on function public.portal_lay_du_lieu(text,text) to anon, authenticated;
grant execute on function public.portal_gui_phuc_khao(text,text,bigint,text) to anon, authenticated;
grant execute on function public.qlnn_xac_nhan_admin(text,text) to anon, authenticated;
grant execute on function public.admin_nhap_ket_qua(text,text,jsonb) to anon, authenticated;
grant execute on function public.admin_lay_ket_qua(text,text) to anon, authenticated;
grant execute on function public.admin_lay_phuc_khao(text,text) to anon, authenticated;
grant execute on function public.admin_cap_nhat_phuc_khao(text,text,bigint,text,text) to anon, authenticated;
revoke all on function public.qlnn_xac_nhan_admin(text,text) from public,anon,authenticated;
