-- V3.0.5.25.25: thông báo chủ động, lịch sử điểm phúc khảo và thông báo theo lớp.
create table if not exists public.qlnn_thong_bao (
 id bigint generated by default as identity primary key,
 ma_hs varchar not null,
 tieu_de text not null,
 noi_dung text not null,
 loai text not null default 'Thông báo',
 nguoi_gui text,
 created_at timestamptz not null default now(),
 da_doc_at timestamptz,
 hien_popup boolean not null default false,
 hien_chay_ngang boolean not null default true,
 lien_ket text
);
create index if not exists idx_qlnn_thong_bao_ma_hs on public.qlnn_thong_bao(ma_hs,created_at desc);
alter table public.qlnn_thong_bao enable row level security;
revoke all on public.qlnn_thong_bao from anon, authenticated;

create table if not exists public.ket_qua_kiem_tra_lich_su (
 id bigint generated by default as identity primary key,
 ket_qua_id bigint not null references public.ket_qua_kiem_tra(id) on delete cascade,
 ma_hs varchar not null,
 diem_cu numeric(4,2), diem_moi numeric(4,2) not null,
 ghi_chu text,
 nguoi_cap_nhat text,
 created_at timestamptz not null default now()
);
alter table public.ket_qua_kiem_tra_lich_su enable row level security;
revoke all on public.ket_qua_kiem_tra_lich_su from anon, authenticated;

create or replace function public.qlnn_notify_score_change() returns trigger language plpgsql security definer set search_path=public as $$
declare nm text;
begin
 if TG_OP='INSERT' then
  insert into public.qlnn_thong_bao(ma_hs,tieu_de,noi_dung,loai,hien_popup,hien_chay_ngang,lien_ket)
  values(new.ma_hs,'Có kết quả kiểm tra mới','Nhà trường đã đăng tải kết quả môn '||new.mon||' của đợt '||new.dot_kiem_tra||'. Điểm: '||new.diem||coalesce('. Ghi chú: '||nullif(new.ghi_chu,''),''),'Kết quả học tập',true,true,'results');
 elsif new.diem is distinct from old.diem or new.ghi_chu is distinct from old.ghi_chu then
  insert into public.ket_qua_kiem_tra_lich_su(ket_qua_id,ma_hs,diem_cu,diem_moi,ghi_chu,nguoi_cap_nhat)
  values(new.id,new.ma_hs,old.diem,new.diem,nullif(new.ghi_chu,''),'Quản trị hệ thống');
  insert into public.qlnn_thong_bao(ma_hs,tieu_de,noi_dung,loai,hien_popup,hien_chay_ngang,lien_ket)
  values(new.ma_hs,case when new.diem is distinct from old.diem then 'Kết quả học tập đã được cập nhật' else 'Ghi chú kết quả đã được cập nhật' end,
  'Môn '||new.mon||' · Đợt '||new.dot_kiem_tra||'. Điểm cũ: '||old.diem||'; điểm mới: '||new.diem||'.'||coalesce(' Ghi chú mới: '||nullif(new.ghi_chu,''),''),'Kết quả học tập',true,true,'results');
 end if;
 return new;
end $$;
drop trigger if exists trg_qlnn_notify_score_change on public.ket_qua_kiem_tra;
create trigger trg_qlnn_notify_score_change after insert or update of diem,ghi_chu on public.ket_qua_kiem_tra for each row execute function public.qlnn_notify_score_change();

create or replace function public.qlnn_notify_discipline_change() returns trigger language plpgsql security definer set search_path=public as $$
begin
 if new.ma_hs is not null and (TG_OP='INSERT' or new.diem is distinct from old.diem or new.chi_tiet is distinct from old.chi_tiet or new.trang_thai is distinct from old.trang_thai) then
  insert into public.qlnn_thong_bao(ma_hs,tieu_de,noi_dung,loai,hien_popup,hien_chay_ngang,lien_ket)
  values(new.ma_hs,'Cập nhật nề nếp / thi đua',coalesce(nullif(new.chi_tiet,''),nullif(new.trang_thai,''),'Có bản ghi nề nếp mới')||'. Điểm: '||coalesce(new.diem::text,'0')||'.','Nề nếp',false,true,'discipline');
 end if;
 return new;
end $$;
drop trigger if exists trg_qlnn_notify_discipline_change on public.diem_danh_master;
create trigger trg_qlnn_notify_discipline_change after insert or update of diem,chi_tiet,trang_thai on public.diem_danh_master for each row execute function public.qlnn_notify_discipline_change();

create or replace function public.portal_lay_du_lieu(p_ma_hs text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.danh_sach%rowtype; r jsonb; n jsonb; a jsonb; t jsonb;
begin
 select * into s from public.danh_sach d where btrim(d.ma_hs)=btrim(p_ma_hs) and btrim(coalesce(d.mat_khau,''))=btrim(coalesce(p_mat_khau,'')) and (d.trang_thai is null or lower(btrim(d.trang_thai)) not in ('inactive','nghi hoc','đã nghỉ','false','0')) limit 1;
 if not found then return null; end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.dot_kiem_tra desc,x.mon),'[]'::jsonb) into r from public.ket_qua_kiem_tra x where x.ma_hs=s.ma_hs;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.ngay_diem_danh desc),'[]'::jsonb) into n from public.diem_danh_master x where x.ma_hs=s.ma_hs;
 select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('mon',q.mon,'dot_kiem_tra',q.dot_kiem_tra,'diem',q.diem,'ghi_chu_ket_qua',q.ghi_chu) order by p.created_at desc),'[]'::jsonb) into a from public.phuc_khao_kiem_tra p join public.ket_qua_kiem_tra q on q.id=p.ket_qua_id where p.ma_hs=s.ma_hs;
 select coalesce(jsonb_agg(to_jsonb(z) order by z.created_at desc),'[]'::jsonb) into t from (select id,tieu_de,noi_dung,loai,nguoi_gui,created_at,da_doc_at,hien_popup,hien_chay_ngang,lien_ket from public.qlnn_thong_bao where ma_hs=s.ma_hs order by created_at desc limit 100) z;
 return jsonb_build_object('hoc_sinh',jsonb_build_object('ma_hs',s.ma_hs,'ho_ten',s.ho_ten,'khoi',s.khoi,'lop',s.lop),'ket_qua',r,'ne_nep',n,'phuc_khao',a,'thong_bao',t);
end $$;

create or replace function public.portal_danh_dau_da_doc(p_ma_hs text,p_mat_khau text,p_ids bigint[])
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 if not exists(select 1 from public.danh_sach d where btrim(d.ma_hs)=btrim(p_ma_hs) and btrim(coalesce(d.mat_khau,''))=btrim(coalesce(p_mat_khau,''))) then return jsonb_build_object('ok',false,'message','Tài khoản không hợp lệ.'); end if;
 update public.qlnn_thong_bao set da_doc_at=now() where ma_hs=btrim(p_ma_hs) and id=any(coalesce(p_ids,'{}'::bigint[])) and da_doc_at is null;
 return jsonb_build_object('ok',true);
end $$;

create or replace function public.admin_gui_thong_bao(p_ma_cb text,p_mat_khau text,p_tieu_de text,p_noi_dung text,p_pham_vi text,p_lop text,p_popup boolean,p_ticker boolean)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c public.can_bo%rowtype; isadmin boolean; isgvcn boolean; n integer:=0; x record;
begin
 select * into c from public.can_bo where btrim(ma_cb)=btrim(p_ma_cb) and coalesce(mat_khau,'')=coalesce(p_mat_khau,'') and coalesce(trang_thai,true)=true limit 1;
 if not found then return jsonb_build_object('ok',false,'message','Không xác thực được tài khoản cán bộ.'); end if;
 isadmin:=lower(coalesce(c.vai_tro,'')) in ('admin','quản trị hệ thống') or coalesce(c.vai_tro_list,'{}'::text[]) @> array['Admin']::text[];
 isgvcn:=lower(coalesce(c.vai_tro,'')) in ('gvcn','giáo viên chủ nhiệm') or coalesce(c.vai_tro_list,'{}'::text[]) && array['GVCN','Giáo viên chủ nhiệm']::text[];
 if not isadmin and not isgvcn then return jsonb_build_object('ok',false,'message','Chỉ Admin hoặc giáo viên chủ nhiệm được gửi thông báo.'); end if;
 if length(btrim(coalesce(p_tieu_de,'')))<3 or length(btrim(coalesce(p_noi_dung,'')))<3 then return jsonb_build_object('ok',false,'message','Cần nhập tiêu đề và nội dung thông báo.'); end if;
 if p_pham_vi='Toàn trường' and not isadmin then return jsonb_build_object('ok',false,'message','Chỉ Admin được gửi thông báo toàn trường.'); end if;
 if p_pham_vi='Lớp' and not isadmin and coalesce(c.lop_quan_ly,'')<>coalesce(p_lop,'') then return jsonb_build_object('ok',false,'message','GVCN chỉ được gửi thông báo cho lớp chủ nhiệm.'); end if;
 if p_pham_vi not in ('Toàn trường','Lớp','Học sinh') then return jsonb_build_object('ok',false,'message','Phạm vi không hợp lệ.'); end if;
 if p_pham_vi='Học sinh' and not isadmin and not exists(select 1 from public.danh_sach d where d.ma_hs=p_lop and d.lop=c.lop_quan_ly) then return jsonb_build_object('ok',false,'message','GVCN chỉ được gửi thông báo cho học sinh lớp chủ nhiệm.'); end if;
 for x in select d.ma_hs from public.danh_sach d where (p_pham_vi='Toàn trường' or (p_pham_vi='Lớp' and d.lop=p_lop) or (p_pham_vi='Học sinh' and d.ma_hs=p_lop)) and (d.trang_thai is null or lower(btrim(d.trang_thai)) not in ('inactive','nghi hoc','đã nghỉ','false','0')) loop
  insert into public.qlnn_thong_bao(ma_hs,tieu_de,noi_dung,loai,nguoi_gui,hien_popup,hien_chay_ngang,lien_ket) values(x.ma_hs,btrim(p_tieu_de),btrim(p_noi_dung),'Thông báo',c.ho_ten,p_popup,p_ticker,'notices'); n:=n+1;
 end loop;
 return jsonb_build_object('ok',true,'count',n);
end $$;

create or replace function public.admin_cap_nhat_phuc_khao_v2(p_ma_cb text,p_mat_khau text,p_id bigint,p_trang_thai text,p_phan_hoi text,p_diem_moi numeric,p_ghi_chu_ket_qua text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare q public.phuc_khao_kiem_tra%rowtype; r public.ket_qua_kiem_tra%rowtype;
begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 if p_trang_thai not in ('Đã gửi','Đang xem xét','Đã xử lý','Từ chối') then return jsonb_build_object('ok',false,'message','Trạng thái không hợp lệ.'); end if;
 select * into q from public.phuc_khao_kiem_tra where id=p_id; if not found then return jsonb_build_object('ok',false,'message','Không tìm thấy yêu cầu phúc khảo.'); end if;
 if p_diem_moi is not null and (p_diem_moi<0 or p_diem_moi>10) then return jsonb_build_object('ok',false,'message','Điểm mới phải từ 0 đến 10.'); end if;
 if p_diem_moi is not null and length(btrim(coalesce(p_ghi_chu_ket_qua,'')))<3 then return jsonb_build_object('ok',false,'message','Cần ghi chú giải thích khi cập nhật điểm mới.'); end if;
 update public.phuc_khao_kiem_tra set trang_thai=p_trang_thai,phan_hoi=nullif(btrim(p_phan_hoi),''),updated_at=now() where id=p_id;
 insert into public.qlnn_thong_bao(ma_hs,tieu_de,noi_dung,loai,hien_popup,hien_chay_ngang,lien_ket) values(q.ma_hs,'Cập nhật yêu cầu phúc khảo','Yêu cầu phúc khảo của bạn đã được cập nhật trạng thái: '||p_trang_thai||coalesce('. Phản hồi: '||nullif(btrim(p_phan_hoi),''),''),'Phúc khảo',true,true,'appeals');
 if p_diem_moi is not null then
  select * into r from public.ket_qua_kiem_tra where id=q.ket_qua_id;
  update public.ket_qua_kiem_tra set diem=p_diem_moi,ghi_chu=btrim(p_ghi_chu_ket_qua),updated_at=now() where id=q.ket_qua_id;
 end if;
 return jsonb_build_object('ok',true);
end $$;

grant execute on function public.portal_lay_du_lieu(text,text) to anon,authenticated;
grant execute on function public.portal_danh_dau_da_doc(text,text,bigint[]) to anon,authenticated;
grant execute on function public.admin_gui_thong_bao(text,text,text,text,text,text,boolean,boolean) to anon,authenticated;
grant execute on function public.admin_cap_nhat_phuc_khao_v2(text,text,bigint,text,text,numeric,text) to anon,authenticated;

-- Bổ sung ghi chú kết quả vào danh sách quản trị để đối chiếu sau cập nhật.
create or replace function public.admin_lay_ket_qua(p_ma_cb text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare r jsonb; begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.dot_kiem_tra desc,x.ma_hs,x.mon),'[]'::jsonb) into r from (select ma_hs,dot_kiem_tra,mon,diem,ngay_kiem_tra,loai_kiem_tra,ghi_chu,updated_at from public.ket_qua_kiem_tra order by dot_kiem_tra desc limit 1000) x;
 return jsonb_build_object('ok',true,'rows',r);
end $$;

create or replace function public.admin_lay_phuc_khao(p_ma_cb text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare r jsonb; begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into r from (select p.id,p.ket_qua_id,p.ma_hs,p.ly_do,p.trang_thai,p.phan_hoi,p.created_at,q.mon,q.dot_kiem_tra,q.diem,q.ghi_chu as ghi_chu_ket_qua,q.id as ket_result_id from public.phuc_khao_kiem_tra p join public.ket_qua_kiem_tra q on q.id=p.ket_qua_id order by p.created_at desc limit 1000) x;
 return jsonb_build_object('ok',true,'rows',r);
end $$;
grant execute on function public.admin_lay_ket_qua(text,text) to anon,authenticated;
grant execute on function public.admin_lay_phuc_khao(text,text) to anon,authenticated;
