-- V3.0.5.25.29: thời hạn phúc khảo theo từng đợt, checkbox tại bảng điểm, ảnh minh chứng.
create table if not exists public.thoi_gian_phuc_khao (
 id bigint generated by default as identity primary key,
 nam_hoc text not null default '2026-2027',
 dot_kiem_tra text not null,
 bat_dau timestamptz not null,
 ket_thuc timestamptz not null,
 nguoi_cap_nhat text,
 updated_at timestamptz not null default now(),
 constraint thoi_gian_phuc_khao_dates check (ket_thuc > bat_dau),
 unique(nam_hoc,dot_kiem_tra)
);
alter table public.phuc_khao_kiem_tra add column if not exists anh_minh_chung text;
alter table public.phuc_khao_kiem_tra enable row level security;
alter table public.thoi_gian_phuc_khao enable row level security;
revoke all on public.thoi_gian_phuc_khao from anon, authenticated;

create or replace function public.admin_dat_thoi_gian_phuc_khao(
 p_ma_cb text,p_mat_khau text,p_nam_hoc text,p_dot_kiem_tra text,p_bat_dau timestamptz,p_ket_thuc timestamptz
) returns jsonb language plpgsql security definer set search_path=public as $$
declare c public.can_bo%rowtype;
begin
 select * into c from public.can_bo where btrim(ma_cb)=btrim(p_ma_cb) and coalesce(mat_khau,'')=coalesce(p_mat_khau,'') and coalesce(trang_thai,true)=true limit 1;
 if not found or not (lower(coalesce(c.vai_tro,'')) in ('admin','quản trị hệ thống') or coalesce(c.vai_tro_list,'{}'::text[]) @> array['Admin']::text[]) then
  return jsonb_build_object('ok',false,'message','Chỉ Admin được thiết lập thời hạn phúc khảo.');
 end if;
 if nullif(btrim(p_dot_kiem_tra),'') is null or p_bat_dau is null or p_ket_thuc is null or p_ket_thuc<=p_bat_dau then
  return jsonb_build_object('ok',false,'message','Tên đợt và thời gian không hợp lệ.');
 end if;
 insert into public.thoi_gian_phuc_khao(nam_hoc,dot_kiem_tra,bat_dau,ket_thuc,nguoi_cap_nhat,updated_at)
 values(coalesce(nullif(btrim(p_nam_hoc),''),'2026-2027'),btrim(p_dot_kiem_tra),p_bat_dau,p_ket_thuc,c.ma_cb,now())
 on conflict(nam_hoc,dot_kiem_tra) do update set bat_dau=excluded.bat_dau,ket_thuc=excluded.ket_thuc,nguoi_cap_nhat=excluded.nguoi_cap_nhat,updated_at=now();
 return jsonb_build_object('ok',true);
end $$;

create or replace function public.portal_gui_phuc_khao_v2(
 p_ma_hs text,p_mat_khau text,p_ket_qua_id bigint,p_anh_minh_chung text default null
) returns jsonb language plpgsql security definer set search_path=public as $$
declare s public.danh_sach%rowtype; q public.ket_qua_kiem_tra%rowtype; w public.thoi_gian_phuc_khao%rowtype; new_id bigint;
begin
 select * into s from public.danh_sach d where btrim(d.ma_hs)=btrim(p_ma_hs) and btrim(coalesce(d.mat_khau,''))=btrim(coalesce(p_mat_khau,'')) and (d.trang_thai is null or lower(btrim(d.trang_thai)) not in ('inactive','nghi hoc','đã nghỉ','false','0')) limit 1;
 if not found then return jsonb_build_object('ok',false,'message','Tài khoản không hợp lệ.'); end if;
 select * into q from public.ket_qua_kiem_tra where id=p_ket_qua_id and ma_hs=s.ma_hs;
 if not found then return jsonb_build_object('ok',false,'message','Bài kiểm tra không thuộc tài khoản này.'); end if;
 select * into w from public.thoi_gian_phuc_khao where nam_hoc=q.nam_hoc and dot_kiem_tra=q.dot_kiem_tra;
 if not found then return jsonb_build_object('ok',false,'message','Đợt kiểm tra này chưa được thiết lập thời gian phúc khảo.'); end if;
 if now()<w.bat_dau then return jsonb_build_object('ok',false,'message','Chưa đến thời gian nhận phúc khảo. Bắt đầu từ '||to_char(w.bat_dau at time zone 'Asia/Ho_Chi_Minh','DD/MM/YYYY HH24:MI')||'.'); end if;
 if now()>w.ket_thuc then return jsonb_build_object('ok',false,'message','Đã hết hạn phúc khảo của đợt kiểm tra này.'); end if;
 if p_anh_minh_chung is not null and (length(p_anh_minh_chung)>1400000 or p_anh_minh_chung !~ '^data:image/(jpeg|png|webp);base64,') then
  return jsonb_build_object('ok',false,'message','Ảnh minh chứng không hợp lệ hoặc vượt quá dung lượng cho phép (1 MB).');
 end if;
 insert into public.phuc_khao_kiem_tra(ket_qua_id,ma_hs,ly_do,anh_minh_chung) values(q.id,s.ma_hs,'Đề nghị phúc khảo',p_anh_minh_chung) returning id into new_id;
 return jsonb_build_object('ok',true,'id',new_id);
exception when unique_violation then return jsonb_build_object('ok',false,'message','Môn học này đã có yêu cầu phúc khảo.');
 when others then return jsonb_build_object('ok',false,'message','Không gửi được yêu cầu: '||sqlerrm);
end $$;

create or replace function public.portal_lay_du_lieu_v3(p_ma_hs text,p_mat_khau text,p_doi_tuong text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r jsonb; results jsonb; appeals jsonb;
begin
 if p_doi_tuong not in ('Học sinh','Phụ huynh') then return null; end if;
 r:=public.portal_lay_du_lieu_v2(p_ma_hs,p_mat_khau,p_doi_tuong);
 if r is null then return null; end if;
 select coalesce(jsonb_agg(to_jsonb(q)||jsonb_build_object('phuc_khao_tu',w.bat_dau,'phuc_khao_den',w.ket_thuc) order by q.dot_kiem_tra desc,q.mon),'[]'::jsonb)
 into results from public.ket_qua_kiem_tra q left join public.thoi_gian_phuc_khao w on w.nam_hoc=q.nam_hoc and w.dot_kiem_tra=q.dot_kiem_tra
 where q.ma_hs=btrim(p_ma_hs);
 select coalesce(jsonb_agg(to_jsonb(p)||jsonb_build_object('mon',q.mon,'dot_kiem_tra',q.dot_kiem_tra,'diem',q.diem,'anh_minh_chung',p.anh_minh_chung is not null) order by p.created_at desc),'[]'::jsonb)
 into appeals from public.phuc_khao_kiem_tra p join public.ket_qua_kiem_tra q on q.id=p.ket_qua_id where p.ma_hs=btrim(p_ma_hs);
 r:=jsonb_set(r,'{ket_qua}',results,true);
 r:=jsonb_set(r,'{phuc_khao}',appeals,true);
 return r;
end $$;

grant execute on function public.admin_dat_thoi_gian_phuc_khao(text,text,text,text,timestamptz,timestamptz) to anon,authenticated;
grant execute on function public.portal_gui_phuc_khao_v2(text,text,bigint,text) to anon,authenticated;
grant execute on function public.portal_lay_du_lieu_v3(text,text,text) to anon,authenticated;


create or replace function public.admin_lay_phuc_khao(p_ma_cb text,p_mat_khau text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r jsonb;
begin
 if not public.qlnn_xac_nhan_admin(p_ma_cb,p_mat_khau) then return jsonb_build_object('ok',false,'message','Không có quyền quản trị.'); end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb) into r
 from (select p.id,p.ket_qua_id,p.ma_hs,p.ly_do,p.trang_thai,p.phan_hoi,p.created_at,p.anh_minh_chung,q.mon,q.dot_kiem_tra,q.diem,q.id as ket_result_id
       from public.phuc_khao_kiem_tra p join public.ket_qua_kiem_tra q on q.id=p.ket_qua_id order by p.created_at desc limit 1000) x;
 return jsonb_build_object('ok',true,'rows',r);
end $$;
grant execute on function public.admin_lay_phuc_khao(text,text) to anon,authenticated;
